service: app-api

frameworkVersion: "3"

package:
  individually: true

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-associate-waf
  - serverless-stack-termination-protection
  - serverless-iam-helper
  - serverless-api-client-certificate
  - serverless-offline
  - "@enterprise-cmcs/serverless-waf-plugin"

custom:
  project: "hcbs"
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"
  stage: ${sls:stage}
  region: ${aws:region}
  wafPlugin:
    name: ${self:service}-${self:custom.stage}-webacl-waf
  wafExcludeRules:
    awsCommon:
      - "SizeRestrictions_BODY"
  serverlessTerminationProtection:
    stages:
      - main
      - val
      - production
  dotenv:
    path: ../../.env
  qmReportTableName: ${env:QM_REPORT_TABLE_NAME, param:QmReportTableName}
  webAclName: ${self:service}-${self:custom.stage}-webacl-waf
  associateWaf:
    name: ${self:custom.webAclName}
    version: V2
  serverlessApiClientCertificate:
    rotateCerts: true
    daysLeft: 30
  authValue:
    main: aws_iam
    val: aws_iam
    production: aws_iam

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  tracing:
    apiGateway: true
  logs:
    restApi: true
  iam:
    role:
      path: ${env:IAM_PATH, ssm:/configuration/${self:custom.stage}/iam/path, ssm:/configuration/default/iam/path, "/"}
      permissionsBoundary: ${env:IAM_PERMISSIONS_BOUNDARY, ssm:/configuration/${self:custom.stage}/iam/permissionsBoundaryPolicy, ssm:/configuration/default/iam/permissionsBoundaryPolicy, ""}
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"
        - Effect: "Allow"
          Action:
            - ssm:GetParameter
          Resource: "*"
        - Effect: "Allow"
          Action:
            - execute-api:Invoke
          Resource: "*"
  environment:
    STAGE: ${self:custom.stage}
    QM_REPORT_TABLE_NAME: ${self:custom.qmReportTableName}

functions:
  getHelloWorld:
    handler: handlers/helloWorld/get.getHelloWorld
    events:
      - http:
          path: helloWorld
          method: get
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
  createReport:
    handler: handlers/reports/create.createReport
    events:
      - http:
          path: reports/{reportType}/{state}
          method: post
          cors: true
          authorizer: aws_iam
          request:
            parameters:
              paths:
                reportType: true
                state: true
  getReport:
    handler: handlers/reports/get.get
    events:
      - http:
          path: reports/{reportType}/{state}/{id}
          method: get
          cors: true
          authorizer: aws_iam
          request:
            parameters:
              paths:
                reportType: true
                state: true
                id: true
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId: !Ref ApiGatewayRestApi
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId: !Ref ApiGatewayRestApi
  Outputs:
    ApiGatewayRestApiName:
      Value: !Ref ApiGatewayRestApi
    ApiGatewayRestApiUrl:
      Value: !Sub https://${ApiGatewayRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:custom.stage}
    Region:
      Value: !Sub ${AWS::Region}
