import { CMIT } from "../../types/reports";
import {
  DataSource,
  DeliverySystem,
  MeasureSpecification,
} from "../../utils/constants";

export const CMIT_LIST: CMIT[] = [
  // required measures
  {
    cmit: 960,
    measureName: "LTSS-1",
    measureTitle: "Comprehensive Assessment and Update",
    defaultDeliveryMethods: true,
    uid: "960",
    measureSteward: "CMS",
    measureSpecification: [
      MeasureSpecification.CMS,
      MeasureSpecification.HEDIS,
    ],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Hybrid,
  },
  {
    cmit: 961,
    measureName: "LTSS-2",
    measureTitle: "Comprehensive Person-Centered Plan and Update",
    defaultDeliveryMethods: true,
    uid: "961",
    measureSteward: "CMS",
    measureSpecification: [
      MeasureSpecification.CMS,
      MeasureSpecification.HEDIS,
    ],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Hybrid,
  },
  {
    cmit: 20,
    measureName: "LTSS-6",
    measureTitle: "Admission to a Facility from the Community",
    defaultDeliveryMethods: true,
    uid: "20",
    measureSteward: "CMS",
    measureSpecification: [MeasureSpecification.CMS],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Administrative,
  },
  {
    cmit: 968,
    measureName: "LTSS-7",
    measureTitle: "Minimizing Facility Length of Stay",
    defaultDeliveryMethods: true,
    uid: "968",
    measureSteward: "CMS",
    measureSpecification: [MeasureSpecification.CMS],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Administrative,
  },
  {
    cmit: 414,
    measureName: "LTSS-8",
    measureTitle: "Successful Transition after Long-Term Facility Stay",
    defaultDeliveryMethods: true,
    uid: "414",
    measureSteward: "CMS",
    measureSpecification: [MeasureSpecification.CMS],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Administrative,
  },
  // optional measures
  {
    cmit: 969,
    measureName: "FASI-1",
    measureTitle: "Identification of Person-Centered Priorities",
    defaultDeliveryMethods: true,
    uid: "969",
    measureSteward: "CMS",
    measureSpecification: [MeasureSpecification.CMS],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.RecordReview,
  },
  {
    cmit: 970,
    measureName: "FASI-2",
    measureTitle: "Documentation of a Person-Centered Service Plan",
    defaultDeliveryMethods: true,
    uid: "970",
    measureSteward: "CMS",
    measureSpecification: [MeasureSpecification.CMS],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.RecordReview,
  },
  {
    cmit: 111,
    measureName: "HCBS-10",
    measureTitle:
      "Self-direction of Services and Supports Among Medicaid Beneficiaries Receiving LTSS through Managed Care Organizations",
    defaultDeliveryMethods: true,
    uid: "111",
    measureSteward: "CMS",
    measureSpecification: [MeasureSpecification.CMS],
    deliverySystem: [DeliverySystem.MLTSS],
    dataSource: DataSource.CaseRecordManagement,
  },
  {
    cmit: 963,
    measureName: "LTSS-3",
    measureTitle: "Shared Person-Centered Plan with Primary Care Provider",
    defaultDeliveryMethods: true,
    uid: "963",
    measureSteward: "CMS",
    measureSpecification: [
      MeasureSpecification.CMS,
      MeasureSpecification.HEDIS,
    ],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Hybrid,
  },
  {
    cmit: 962,
    measureName: "LTSS-4",
    measureTitle:
      "Reassessment and Person-Centered Plan Update after Inpatient Discharge",
    defaultDeliveryMethods: true,
    uid: "962",
    measureSteward: "CMS",
    measureSpecification: [
      MeasureSpecification.CMS,
      MeasureSpecification.HEDIS,
    ],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Hybrid,
  },
  {
    cmit: 1255,
    measureName: "LTSS-5",
    measureTitle:
      "Screening, Risk Assessment, and Plan of Care to Prevent Future Falls",
    defaultDeliveryMethods: false,
    deliveryMethodTitles: [
      "Part 1: Screening (MLTSS)",
      "Risk Assessment and Plan of Care to Prevent Future Falls (MLTSS)",
    ],
    uid: "1255",
    measureSteward: "CMS",
    measureSpecification: [MeasureSpecification.CMS],
    deliverySystem: [DeliverySystem.MLTSS, DeliverySystem.MLTSS],
    dataSource: DataSource.Hybrid,
  },
  {
    cmit: 561,
    measureName: "MLTSS",
    measureTitle: "Plan All-Cause Readmission",
    defaultDeliveryMethods: true,
    uid: "561",
    measureSteward: "NCQA",
    measureSpecification: [MeasureSpecification.HEDIS],
    deliverySystem: [DeliverySystem.MLTSS],
    dataSource: DataSource.Administrative,
  },
  // POM measures
  {
    cmit: 1822,
    measureName: "POM",
    measureTitle: "People Live in Integrated Environments",
    defaultDeliveryMethods: true,
    uid: "1822-1",
    measureSteward: "CQL",
    measureSpecification: [MeasureSpecification.CQL],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Survey,
  },
  {
    cmit: 1822,
    measureName: "POM",
    measureTitle: "People Participate in the Life of the Community",
    defaultDeliveryMethods: true,
    uid: "1822-2",
    measureSteward: "CQL",
    measureSpecification: [MeasureSpecification.CQL],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Survey,
  },
  {
    cmit: 1822,
    measureName: "POM",
    measureTitle: "People Choose Services",
    defaultDeliveryMethods: true,
    uid: "1822-3",
    measureSteward: "CQL",
    measureSpecification: [MeasureSpecification.CQL],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Survey,
  },
  {
    cmit: 1822,
    measureName: "POM",
    measureTitle: "People Realize Personal Goals",
    defaultDeliveryMethods: true,
    uid: "1822-4",
    measureSteward: "CQL",
    measureSpecification: [MeasureSpecification.CQL],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Survey,
  },
  {
    cmit: 1822,
    measureName: "POM",
    measureTitle: "People are Free from Abuse and Neglect",
    defaultDeliveryMethods: true,
    uid: "1822-5",
    measureSteward: "CQL",
    measureSpecification: [MeasureSpecification.CQL],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Survey,
  },
  {
    cmit: 1822,
    measureName: "POM",
    measureTitle: "People Have the Best Possible Health",
    defaultDeliveryMethods: true,
    uid: "1822-6",
    measureSteward: "CQL",
    measureSpecification: [MeasureSpecification.CQL],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Survey,
  },
  {
    cmit: 1822,
    measureName: "POM",
    measureTitle: "People Interact with Other Members of the Community",
    defaultDeliveryMethods: true,
    uid: "1822-7",
    measureSteward: "CQL",
    measureSpecification: [MeasureSpecification.CQL],
    deliverySystem: [DeliverySystem.FFS, DeliverySystem.MLTSS],
    dataSource: DataSource.Survey,
  },
];
