import { WAIVER, WaiverType } from "../../types/reports";

/** The ids are generate from https://shortunique.id/. 
 * Waivers don't change completely from year to year so this file is meant to be copied over to the next year and only the ones that changed get modified
 */

export const WAIVER_LIST: WAIVER[] = [
  {
    id: "ayL8O0",
    state: "AK",
    controlNumber: "AK.0260.06.02",
    programTitle: "People with Intellectual and Developmental Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "extYh5",
    state: "AK",
    controlNumber: "AK.0261.06.00",
    programTitle: "Alaskans Living Independently",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "wcJvyr",
    state: "AK",
    controlNumber: "AK.0262.06.02",
    programTitle: "Adults with Physical and Developmental Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "JqObR8",
    state: "AK",
    controlNumber: "AK.0263.06.02",
    programTitle: "Children with Complex Medical Conditions",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "FHwcZq",
    state: "AK",
    controlNumber: "AK.1566.00.15",
    programTitle: "Individualized Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "sf7g7b",
    state: "AK",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    id: "1LmDNG",
    state: "AL",
    controlNumber: "AL.0001.09.05",
    programTitle:
      "Alabama Home and Community-Based Waiver for Persons with Intellectual Disabilities (ID Waiver)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "L6pZ8y",
    state: "AL",
    controlNumber: "AL.0241.06.01",
    programTitle: "SAIL Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "MMXrxj",
    state: "AL",
    controlNumber: "AL.0391.04.05",
    programTitle:
      "Alabama HCBS Living at Home Waiver for Persons with Intellectual Disabilities (LAH Waiver)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "fayfDZ",
    state: "AL",
    controlNumber: "AL.0407.04.00",
    programTitle: "Technology Assisted Waiver-TA Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "hgGRPg",
    state: "AL",
    controlNumber: "AL.0878.02.00",
    programTitle: "Alabama Community Transition Waiver (ACT Waiver)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "XKm5Pp",
    state: "AL",
    controlNumber: "AL.1746.00.01",
    programTitle: "Community Waiver Program",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "dfpT2c",
    state: "AL",
    controlNumber: "AL.0068.08.00",
    programTitle:
      "Alabama Home and Community -Based Waiver for the Elderly and Disabled Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "HoWdqF",
    state: "AL",
    controlNumber: "",
    programTitle: "1915(j) Self-directed 1915(c) waiver services",
    waiverType: WaiverType.SPA1915J,
  },
  {
    id: "y9Ux9J",
    state: "AR",
    controlNumber: "AR.0195.06.02",
    programTitle: "ARChoices in Homecare",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "W681Jv",
    state: "AR",
    controlNumber: "AR.0400.04.00",
    programTitle: "Living Choices Assisted Living Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "n4O1kb",
    state: "AR",
    controlNumber: "AR.0188.06.01",
    programTitle: "Community and Employment Support Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "XndN8k",
    state: "AR",
    controlNumber: "AR.0936.01.01",
    programTitle: "Autism Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "RaFUSC",
    state: "AR",
    controlNumber: "AR-23-0022",
    programTitle: "Adult Behavioral Health and Community Integration",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "0AmHjI",
    state: "AR",
    controlNumber: "AR-23-0021",
    programTitle: "PASSE",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "9DQEmH",
    state: "AR",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    id: "0K7AQL",
    state: "AR",
    controlNumber: "",
    programTitle: "1915(j) Self-directed 1915(c) waiver services",
    waiverType: WaiverType.SPA1915J,
  },
  {
    id: "KW0hmL",
    state: "AZ",
    controlNumber: "11-W-00275/9",
    programTitle: "Arizona Health Care Cost Containment System (AHCCCS)",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "99trw9",
    state: "CA",
    controlNumber: "CA.1166.01.00",
    programTitle:
      "California Self-Determination Program Waiver for Individuals with Developmental Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Tg4CXU",
    state: "CA",
    controlNumber: "CA.0139.06.00",
    programTitle: "Home and Community Based Alternatives Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "TeUoBN",
    state: "CA",
    controlNumber: "CA.0183.06.00",
    programTitle: "Medi-Cal Waiver Program (MCWP)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "wK15N5",
    state: "CA",
    controlNumber: "CA.0336.04.18",
    programTitle:
      "HCBS Waiver for Californians with Developmental Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "MLwbVC",
    state: "CA",
    controlNumber: "CA.0431.03.09",
    programTitle: "California Assisted Living Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "sayr4C",
    state: "CA",
    controlNumber: "CA.0141.06.08",
    programTitle: "Multipurpose Senior Services Program",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "uU5U3T",
    state: "CA",
    controlNumber: "CA-21-0002",
    programTitle: "Habilitation 1915(i) benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "Yogvl8",
    state: "CA",
    controlNumber: "11-W-00193/9",
    programTitle: "CalAIM",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "kIe9rG",
    state: "CA",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    id: "DMAfKo",
    state: "CA",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    id: "xZsxvM",
    state: "CO",
    controlNumber: "CO.0006.09.03",
    programTitle: "Elderly, Blind and Disabled (HCBS-EBD)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "M26Jar",
    state: "CO",
    controlNumber: "CO.0268.06.03",
    programTitle: "HCBS Waiver for Community Mental Health Supports (CMHS)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "cNSZ1s",
    state: "CO",
    controlNumber: "CO.0288.06.03",
    programTitle: "Persons with Brain Injury (HCBS-BI)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "1GipZn",
    state: "CO",
    controlNumber: "CO.4157.06.21",
    programTitle: "Children's Home and Community Based Services (CHCBS) waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "iQDcmY",
    state: "CO",
    controlNumber: "CO.0007.08.21",
    programTitle: "Developmental Disabilities (HCBS-DD)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "l6diYp",
    state: "CO",
    controlNumber: "CO.0293.05.22",
    programTitle: "Supported Living Services (SLS)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "nFiAxa",
    state: "CO",
    controlNumber: "CO.0305.05.21",
    programTitle: "HCBS - Children's Habilitation Residential Program",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Pdr2ZA",
    state: "CO",
    controlNumber: "CO.4180.05.21",
    programTitle: "Children's Extensive Support (CES) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "e5AkOg",
    state: "CO",
    controlNumber: "CO.0450.03.14",
    programTitle:
      "Colorado's Home and Community Based Services Waiver for Children with Life-Limiting Illness",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "io0CpO",
    state: "CO",
    controlNumber: "CO.0961.02.16",
    programTitle: "Complementary and Integrative Health (HCBS-CIH)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "zbW7Rp",
    state: "CO",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    id: "1DYoYE",
    state: "CT",
    controlNumber: "CT.0140.07.00",
    programTitle: "Home and Community Based Services Waiver for Elders",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Fzed3D",
    state: "CT",
    controlNumber: "CT.0881.02.03",
    programTitle: "Employment and Day Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "prYGq9",
    state: "CT",
    controlNumber: "CT.0302.05.00",
    programTitle: "CT ABI Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "dvpxBn",
    state: "CT",
    controlNumber: "CT.4110.08.00",
    programTitle: "Katie Beckett Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "vHxeHZ",
    state: "CT",
    controlNumber: "CT.0653.03.00",
    programTitle: "Mental Health Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "yugHUH",
    state: "CT",
    controlNumber: "CT.0993.02.00",
    programTitle: "Home and Community Supports Waiver for Persons with Autism",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "gDKlU4",
    state: "CT",
    controlNumber: "CT.0426.04.00",
    programTitle: "Individual and Family Support Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "IdxPuD",
    state: "CT",
    controlNumber: "CT.0437.03.10",
    programTitle: "Comprehensive Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "qTYcpr",
    state: "CT",
    controlNumber: "CT.0301.06.00",
    programTitle: "Personal Care Assistance Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "MrM6aA",
    state: "CT",
    controlNumber: "CT.1085.01.00",
    programTitle: "CT ABI Waiver II",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "0G4mlC",
    state: "CT",
    controlNumber: "CT-22-0001",
    programTitle: "Home Care Program for Elders (CHCPE)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "dbDYt1",
    state: "CT",
    controlNumber: "CT-21-0001",
    programTitle: "CT Housing Engagement & Support Services",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "VdTOYQ",
    state: "CT",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    id: "4NjcyY",
    state: "DC",
    controlNumber: "DC.1766.00.05",
    programTitle: "Individual and Family Support (IFS) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "elAvn9",
    state: "DC",
    controlNumber: "DC.0334.05.02",
    programTitle: "Elderly & Persons With Physical Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "4uXqap",
    state: "DC",
    controlNumber: "DC.0307.05.01",
    programTitle:
      "People with Intellectual and Developmental Disabilities (IDD) Waiver - 2022 Renewal",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "bkrE3b",
    state: "DC",
    controlNumber: "DC-24-0019",
    programTitle: "Adult Day Health",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "flrAYg",
    state: "DC",
    controlNumber: "DC-21-0015",
    programTitle: "Housing Support Services",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "d8JEI0",
    state: "DC",
    controlNumber: "DC-21-0011",
    programTitle: "Behavioral Health Supported Employment",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "gla6xJ",
    state: "DE",
    controlNumber: "DE.0009.08.06",
    programTitle: "DDDS Lifespan Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "mQJexx",
    state: "DE",
    controlNumber: "DE-19-003",
    programTitle: "Pathways to Employment",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "ILwWQa",
    state: "DE",
    controlNumber: "11-W-00036/3",
    programTitle: "Diamond State Health Plan",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "a24KKN",
    state: "FL",
    controlNumber: "FL.40205.03.00",
    programTitle: "Familial Dysautonomia Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "aNDVrt",
    state: "FL",
    controlNumber: "FL.0962.02.00",
    programTitle: "Florida Long-Term Care",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "PYhd37",
    state: "FL",
    controlNumber: "FL.2346.00.00",
    programTitle:
      "Comprehensive Intellectual and Developmental Disabilities Managed Care Pilot Program",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "S3kOGz",
    state: "FL",
    controlNumber: "FL.0867.02.07",
    programTitle: "Developmental Disabilities Individual Budgeting Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "M9juNW",
    state: "FL",
    controlNumber: "FL.40166.06.00",
    programTitle: "Model Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "poUXdP",
    state: "FL",
    controlNumber: "11-W-00206/4",
    programTitle: "Managed Medical Assistance",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "Nkw3HW",
    state: "FL",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    id: "OLBeet",
    state: "FL",
    controlNumber: "",
    programTitle: "1915(j) Self-directed 1915(c) waiver services",
    waiverType: WaiverType.SPA1915J,
  },
  {
    id: "mp2Tdu",
    state: "GA",
    controlNumber: "GA.0323.05.00",
    programTitle: "Comprehensive Supports Waiver Program",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "vGS1ld",
    state: "GA",
    controlNumber: "GA.4170.06.00",
    programTitle: "Independent Care Waiver Program (ICWP) renewal waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "eloiNw",
    state: "GA",
    controlNumber: "GA.0112.08.00",
    programTitle: "Elderly and Disabled Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "yJ2N2f",
    state: "GA",
    controlNumber: "GA.0175.06.01",
    programTitle: "New Options Waiver (NOW)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "kEkCoC",
    state: "HI",
    controlNumber: "HI.0013.08.03",
    programTitle:
      "HCB Services for People with Intellectual and Developmental Disabilities (I/DD Waiver)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "GO1BDg",
    state: "HI",
    controlNumber: "11-W-00001/9",
    programTitle: "Hawaii QUEST Integration",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "02Pmub",
    state: "IA",
    controlNumber: "IA.0345.04.02",
    programTitle:
      "Home and Community Based Services - Physical Disability Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "ZN9OX8",
    state: "IA",
    controlNumber: "IA.4111.07.01",
    programTitle:
      "Home and Community Based Services - Health and Disability (HD) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "x1gJSK",
    state: "IA",
    controlNumber: "IA.0819.02.07",
    programTitle: "The Children's Mental Health Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "iVa1GB",
    state: "IA",
    controlNumber: "IA.4155.06.01",
    programTitle: "Home and Community Based Services - Elderly Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "WOxOjG",
    state: "IA",
    controlNumber: "IA.0242.06.10",
    programTitle:
      "Home and Community Based Services - Intellectual Disabilities (ID) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "DqXjYB",
    state: "IA",
    controlNumber: "IA.0299.05.06",
    programTitle: "Home and Community Based Services - Brain Injury (BI)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "VZAYbW",
    state: "IA",
    controlNumber: "IA.0213.06.00",
    programTitle: "Home and Community Based Services - AIDS/HIV",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "zZCqS8",
    state: "IA",
    controlNumber: "IA-16-0009",
    programTitle: "Habiliation",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "hRxDoC",
    state: "ID",
    controlNumber: "ID.0076.07.00",
    programTitle: "Adult Developmental Disabilities Waiver (renewal)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Ov2zxm",
    state: "ID",
    controlNumber: "ID.1076.07.00",
    programTitle: "Aged and Disabled Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "QVtYXm",
    state: "ID",
    controlNumber: "ID-20-0020",
    programTitle: "Children 1915(i)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "eMRSvW",
    state: "ID",
    controlNumber: "ID-22-0009",
    programTitle: "YES (children with SED)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "TaOdjm",
    state: "ID",
    controlNumber: "ID-22-0022",
    programTitle: "Adult DD",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "R7V956",
    state: "IL",
    controlNumber: "IL.0142.07.05",
    programTitle: "Persons with Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "kftEKh",
    state: "IL",
    controlNumber: "IL.0143.07.03",
    programTitle: "Persons who are Elderly",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "st2wz0",
    state: "IL",
    controlNumber: "IL.0329.05.02",
    programTitle: "Persons with Brain Injury",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "OYrr5d",
    state: "IL",
    controlNumber: "IL.0350.05.01",
    programTitle: "Adults with Developmental Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "bPNhp2",
    state: "IL",
    controlNumber: "IL.0464.03.01",
    programTitle:
      "Support Waiver for Children and Young Adults with Developmental Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Rz5qsn",
    state: "IL",
    controlNumber: "IL.0473.03.01",
    programTitle:
      "Residential Waiver for Children and Young Adults with Developmental Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Uzei9s",
    state: "IL",
    controlNumber: "IL.0278.06.00",
    programTitle: "Medically Fragile, Technology Dependent",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "OxFN0a",
    state: "IL",
    controlNumber: "IL.0326.05.00",
    programTitle: "Illinois Supportive Living Program",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "y2j1AZ",
    state: "IL",
    controlNumber: "IL.0202.06.14",
    programTitle: "Persons with HIV or AIDS",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "lN9Rfr",
    state: "IL",
    controlNumber: "IL-22-0021",
    programTitle: "1915(i) HCBS State Plan Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "jC7LgD",
    state: "IN",
    controlNumber: "IN.4197.05.00",
    programTitle: "Traumatic Brain Injury Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "5qOp7T",
    state: "IN",
    controlNumber: "IN.0210.06.10",
    programTitle: "Aged & Disabled Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "hbk6Ps",
    state: "IN",
    controlNumber: "IN.2407.R00.00",
    programTitle: "Pathways Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "qNwvGB",
    state: "IN",
    controlNumber: "IN.0378.04.06",
    programTitle: "Community Integration and Habilitation Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "deJmyL",
    state: "IN",
    controlNumber: "IN.0387.04.06",
    programTitle: "Family Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "cbseek",
    state: "IN",
    controlNumber: "IN-22-0016",
    programTitle: "Children's Mental Health Wraparound Benefit (CMHW)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "hJsLIq",
    state: "IN",
    controlNumber: "IN-23-0002",
    programTitle: "Adult mental Health Wraparound Benefit (AMHH)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "4aHJIc",
    state: "IN",
    controlNumber: "IN-23-0024",
    programTitle:
      "Behavioral and Primary Healthcare Coordination Benefit (BPHC)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "QQnflN",
    state: "KS",
    controlNumber: "KS.0303.05.02",
    programTitle: "Home and Community Based Services for the Frail Elderly",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "PXufR1",
    state: "KS",
    controlNumber: "KS.0304.05.02",
    programTitle: "Kansas Physical Disability Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "JEoE61",
    state: "KS",
    controlNumber: "KS.0320.04.05",
    programTitle: "Serious Emotional Disturbance (SED) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "bpXWiP",
    state: "KS",
    controlNumber: "KS.0476.02.05",
    programTitle: "Autism Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "4JkXlz",
    state: "KS",
    controlNumber: "KS.4165.06.06",
    programTitle: "Technology Assisted Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "2mg8eh",
    state: "KS",
    controlNumber: "KS.0224.06.06",
    programTitle: "Kansas - HCBS-I/DD Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "K6kl8P",
    state: "KS",
    controlNumber: "KS.4164.06.07",
    programTitle: "Kansas HCBS Brain Injury Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "DpsySO",
    state: "KY",
    controlNumber: "KY.0314.04.01",
    programTitle: "Supports for Community Living waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "qWOtvN",
    state: "KY",
    controlNumber: "KY.0333.04.00",
    programTitle: "Acquired Brain Injury Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "BxyzbS",
    state: "KY",
    controlNumber: "KY.0475.02.00",
    programTitle: "Michelle P. Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "BiHKYh",
    state: "KY",
    controlNumber: "KY.0477.02.00",
    programTitle: "Acquired Brain Injury, Long Term Care",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "RPKFGt",
    state: "KY",
    controlNumber: "KY.0144.07.00",
    programTitle: "Home and Community Based Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "DNxuSW",
    state: "KY",
    controlNumber: "KY.40146.07.00",
    programTitle: "Model Waiver II",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "cmngAo",
    state: "KY",
    controlNumber: "KY-24-0010",
    programTitle: "SMI/SUD 1915i Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "8Tt7u0",
    state: "LA",
    controlNumber: "LA.0401.04.01",
    programTitle: "New Opportunities Waiver (NOW)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "VX15vH",
    state: "LA",
    controlNumber: "LA.0121.07.01",
    programTitle: "Adult Day Health Care (ADHC) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "xNmnpA",
    state: "LA",
    controlNumber: "LA.0889.02.00",
    programTitle:
      "Coordinated System of Care (CSoC) Severely Emotionally Disturbed (SED) Children's Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "QcNtWq",
    state: "LA",
    controlNumber: "LA.0472.03.00",
    programTitle: "Residential Options Waiver (ROW)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "TAMDMZ",
    state: "LA",
    controlNumber: "LA.0361.04.12",
    programTitle: "Children's Choice (CC) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "ziByRO",
    state: "LA",
    controlNumber: "LA.0453.03.14",
    programTitle: "Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "8NQtJV",
    state: "LA",
    controlNumber: "LA.0866.02.00",
    programTitle: "Community Choices (CC) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Qshb1w",
    state: "MA",
    controlNumber: "MA.1027.01.01",
    programTitle: "MFP Community Living (MFP-CL)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "XFTSgS",
    state: "MA",
    controlNumber: "MA.1028.01.00",
    programTitle: "MFP Residential Supports (MFP-RS)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "vQMF3P",
    state: "MA",
    controlNumber: "MA.40701.02.01",
    programTitle:
      "Acquired Brain Injury with Residential Habilitation (ABI-RH) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "jeIkmC",
    state: "MA",
    controlNumber: "MA.40702.02.00",
    programTitle:
      "Acquired Brain Injury Non-Residential Habilitation (ABI-N) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "KgrUK6",
    state: "MA",
    controlNumber: "MA.0826.02.08",
    programTitle: "Community Living Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "F5l2ji",
    state: "MA",
    controlNumber: "MA.0827.02.08",
    programTitle: "Intensive Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "E7Jhka",
    state: "MA",
    controlNumber: "MA.0828.02.08",
    programTitle: "Adult Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "9GoS3X",
    state: "MA",
    controlNumber: "MA.0059.07.05",
    programTitle: "Frail Elder Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "yw313M",
    state: "MA",
    controlNumber: "MA.0359.04.05",
    programTitle: "Traumatic Brain Injury Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "vV4Z4n",
    state: "MA",
    controlNumber: "MA.40207.04.00",
    programTitle: "Children's Autism Spectrum Disorder Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Z0o8dz",
    state: "MD",
    controlNumber: "MD.40198.04.00",
    programTitle: "Brain Injury renewal waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "HklUlF",
    state: "MD",
    controlNumber: "MD.0265.06.00",
    programTitle: "Home and Community Based Options Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "xBr2bs",
    state: "MD",
    controlNumber: "MD.0023.08.00",
    programTitle: "Community Pathways Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "YRAB7c",
    state: "MD",
    controlNumber: "MD.0645.02.00",
    programTitle: "Medical Day Care Services Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "5zG3hZ",
    state: "MD",
    controlNumber: "MD.1466.02.01",
    programTitle: "Family Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "xEoAvM",
    state: "MD",
    controlNumber: "MD.1506.02.00",
    programTitle: "Community Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "LV1FAD",
    state: "MD",
    controlNumber: "MD.40118.07.00",
    programTitle: "Model Waiver for Fragile Children",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "S5SD3k",
    state: "MD",
    controlNumber: "MD.0339.04.00",
    programTitle: "Waiver for Children with Autism Spectrum Disorder - Renewal",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "ST6Npg",
    state: "MD",
    controlNumber: "MD-24-0008",
    programTitle: "Children & Youth W/SED",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "xCxD9V",
    state: "MD",
    controlNumber: "11-W-00099/3",
    programTitle: "HealthChoice",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "3si5Dn",
    state: "MD",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    id: "PYNr7h",
    state: "MD",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    id: "R3V3tM",
    state: "ME",
    controlNumber: "ME.0467.03.01",
    programTitle:
      "Support Services for Adults with Intellectual Disabilities or Autism Spectrum Disorder",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Xx3pxI",
    state: "ME",
    controlNumber: "ME.0276.05.06",
    programTitle: "Elderly and Adults with Disabilities Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "pGYYAW",
    state: "ME",
    controlNumber: "ME.0995.01.04",
    programTitle:
      "Home and Community Based Services for Adults with Other Related Conditions",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "tyOL43",
    state: "ME",
    controlNumber: "ME.1082.01.03",
    programTitle:
      "Home and Community Based Services for Members with Brain Injury",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "PekzDU",
    state: "ME",
    controlNumber: "ME.0159.07.06",
    programTitle:
      "Home and Community Services for Adults with Intellectual Disabilities or Autism Spectrum Disorder",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "iHGDty",
    state: "MI",
    controlNumber: "MI.1126.01.02",
    programTitle: "MI Health Link HCBS",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "6hTdmo",
    state: "MI",
    controlNumber: "MI.0233.05.03",
    programTitle: "MI Choice Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "F9m3WA",
    state: "MI",
    controlNumber: "MI.0167.06.00",
    programTitle: "Habilitation Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "U4T5gP",
    state: "MI",
    controlNumber: "MI.0438.03.04",
    programTitle: "Waiver for Children with Serious Emotional Disturbances",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "3uOpOG",
    state: "MI",
    controlNumber: "MI.4119.06.00",
    programTitle: "Children's Waiver Program",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "okasQR",
    state: "MI",
    controlNumber: "MI-24-0008",
    programTitle: "Behavoiral Health",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "1sb4Sv",
    state: "MI",
    controlNumber: "MI-23-0010",
    programTitle: "Nursing Facility Transition",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "e7PgMU",
    state: "MN",
    controlNumber: "MN.0166.07.14",
    programTitle: "Community Access for Disability Inclusion (CADI)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "RaDEdQ",
    state: "MN",
    controlNumber: "MN.4169.06.08",
    programTitle: "Brain Injury (BI) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "ZBDx9v",
    state: "MN",
    controlNumber: "MN.0061.08.01",
    programTitle: "Developmental Disabilities (DD) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "vGX2Kq",
    state: "MN",
    controlNumber: "MN.4128.07.21",
    programTitle: "Community Alternative Care (CAC) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "mq4yYa",
    state: "MN",
    controlNumber: "MN.0025.08.22",
    programTitle: "Elderly Waiver (EW)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "dn2ysH",
    state: "MN",
    controlNumber: "MN-24-0045",
    programTitle: "Housing Stabilization Services Benefit (HSS)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "tMiydz",
    state: "MN",
    controlNumber: "MN-22-0006",
    programTitle: "Community First Services and Supports Benefit (CFSS)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "gClvXr",
    state: "MN",
    controlNumber: "11-W-00286/5",
    programTitle: "Minnesota Reform",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "fNnGat",
    state: "MN",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    id: "aQwSCQ",
    state: "MO",
    controlNumber: "MO.0178.07.05",
    programTitle: "DD Comprehensive Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "tV3FOu",
    state: "MO",
    controlNumber: "MO.0404.04.05",
    programTitle: "Division of DD Community Support Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "X67VYH",
    state: "MO",
    controlNumber: "MO.1706.00.03",
    programTitle: "Structured Family Caregiving",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "6Oa5sb",
    state: "MO",
    controlNumber: "MO.40190.05.01",
    programTitle: "Medically Fragile Adult Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "5jt33f",
    state: "MO",
    controlNumber: "MO.0197.07.00",
    programTitle: "AIDS Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "3aSlXx",
    state: "MO",
    controlNumber: "MO.0026.09.00",
    programTitle: "Aged & Disabled Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "i0qayL",
    state: "MO",
    controlNumber: "MO.0841.02.15",
    programTitle: "Partnership for Hope",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "ddxFaB",
    state: "MO",
    controlNumber: "MO.4185.05.12",
    programTitle:
      "Missouri Children with Developmental Disabilities (MOCDD) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "o7s3Vk",
    state: "MO",
    controlNumber: "MO.0346.04.05",
    programTitle: "Independent Living Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "isKGC4",
    state: "MO",
    controlNumber: "MO.1021.03.00",
    programTitle: "Adult Day Care Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "wUY9ax",
    state: "MO",
    controlNumber: "MO.1406.00.04",
    programTitle: "Brain Injury Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "AyW4CI",
    state: "MS",
    controlNumber: "MS.0255.06.00",
    programTitle: "Independent Living Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "RrVVOv",
    state: "MS",
    controlNumber: "MS.0272.06.00",
    programTitle: "Elderly and Disabled (E&D)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "vltm97",
    state: "MS",
    controlNumber: "MS.0282.05.00",
    programTitle:
      "Intellectual Disabilities/Developmental Disabilities (ID/DD)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "T1lgXv",
    state: "MS",
    controlNumber: "MS.0355.04.00",
    programTitle: "Assisted Living Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "cmiktR",
    state: "MS",
    controlNumber: "MS.0366.04.01",
    programTitle: "Traumatic Brain Injury/Spinal Cord Injury Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "TPVZei",
    state: "MS",
    controlNumber: "MS-23-0018",
    programTitle: "1915(i) HCBS State Plan Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "gyECej",
    state: "MT",
    controlNumber: "MT.0455.03.00",
    programTitle:
      "Severe and Disabling Mental Illness Home and Community Based Services",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Efsdyr",
    state: "MT",
    controlNumber: "MT.0208.06.09",
    programTitle:
      "Home and Community-Based Waiver for Individuals with Developmental Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "TR92kW",
    state: "MT",
    controlNumber: "MT.0148.06.08",
    programTitle: "Montana Big Sky",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "7fRtht",
    state: "MT",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    id: "5hGjVY",
    state: "NC",
    controlNumber: "NC.1326.01.02",
    programTitle: "TBI Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "wUQl9E",
    state: "NC",
    controlNumber: "NC.4141.07.00",
    programTitle: "Community Alternatives Program for Children",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "LXvKXY",
    state: "NC",
    controlNumber: "NC.0423.03.10",
    programTitle: "North Carolina Innovations",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "J7zTM0",
    state: "NC",
    controlNumber: "NC.0132.07.08",
    programTitle: "CAP/DA Renewal (3.5)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "sb6gXm",
    state: "NC",
    controlNumber: "NC-22-0026",
    programTitle: "Mental Health/DD/SUD",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "hijKyd",
    state: "ND",
    controlNumber: "ND.0568.03.00",
    programTitle: "North Dakota Medicaid Waiver for Medically Fragile Children",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "fGIV35",
    state: "ND",
    controlNumber: "ND.0273.06.01",
    programTitle: "Medicaid Waiver for Home and Community Based Services",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "W32w8A",
    state: "ND",
    controlNumber: "ND.0834.02.01",
    programTitle: "Children's Hospice",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "cvyWm9",
    state: "ND",
    controlNumber: "ND.0842.02.05",
    programTitle: "Autism Spectrum Disorder (ASD) Birth through Fifteen",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "QnhZe3",
    state: "ND",
    controlNumber: "ND.0037.08.04",
    programTitle: "Traditional IID/DD Home and Community Based Services Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "P2wVkQ",
    state: "ND",
    controlNumber: "ND-20-0010",
    programTitle: "1915(i) HCBS State Plan Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "umHJW6",
    state: "NE",
    controlNumber: "NE.0187.07.03",
    programTitle:
      "HCBS Waiver for Aged and Adults and Children with Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "lpxIKo",
    state: "NE",
    controlNumber: "NE.0394.04.00",
    programTitle: "Developmental Disabilities Day Services Waiver for Adults",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Se6A9d",
    state: "NE",
    controlNumber: "NE.2366.R00.00",
    programTitle: "Family Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Npz6xB",
    state: "NE",
    controlNumber: "NE.4154.07.00",
    programTitle: "Comprehensive Developmental Disabilities Services waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "1veBLC",
    state: "NE",
    controlNumber: "NE.40199.04.10",
    programTitle: "Traumatic Brain Injury",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "LjLQKh",
    state: "NE",
    controlNumber: "NE-24-0005",
    programTitle: "Therapeutic Family Care Crisis Support Services",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "l60ixS",
    state: "NH",
    controlNumber: "NH.0397.04.00",
    programTitle:
      "NH In Home Supports Waiver for Children with Developmental Disabilities: 2021 - 2025",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "jWoABD",
    state: "NH",
    controlNumber: "NH.0053.07.05",
    programTitle: "New Hampshire Developmental Disabilities Waiver 2021-2026",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Qtj2a3",
    state: "NH",
    controlNumber: "NH.4177.06.05",
    programTitle: "NH Acquired Brain Disorder Waiver 2021-2026",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "0nmbbJ",
    state: "NH",
    controlNumber: "NH.0060.08.01",
    programTitle: "Choices for Independence Waiver Renewal: 2022--->2027",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "okc51P",
    state: "NH",
    controlNumber: "NH 21-0027",
    programTitle: "Supportive Housing",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "RLlDcD",
    state: "NH",
    controlNumber: "NH-22-0038",
    programTitle: "Home and Community-Based Care for High-Risk Children w/ SED",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "7rD4av",
    state: "NH",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    id: "hA7tZv",
    state: "NJ",
    controlNumber: "11-W-00279/2",
    programTitle: "NJ Family Health Care Comphrensive",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "klM4hj",
    state: "NJ",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    id: "5SnVK7",
    state: "NM",
    controlNumber: "NM.1726.00.04",
    programTitle: "Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "LI1ONt",
    state: "NM",
    controlNumber: "NM.0448.03.02",
    programTitle: "Mi Via - ICF/IDD Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "9d0XIV",
    state: "NM",
    controlNumber: "NM.0173.07.02",
    programTitle: "Developmental Disabilities Waiver Program",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "veA5uc",
    state: "NM",
    controlNumber: "NM.0223.06.02",
    programTitle: "Medically Fragile Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "h6rqCX",
    state: "NM",
    controlNumber: "11-W-00285/6",
    programTitle: "Turquoise Care",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "UV9Djo",
    state: "NV",
    controlNumber: "NV.4150.07.00",
    programTitle:
      "Home and Community Based Services (HCBS) Waiver for Persons with Physical Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "DI96an",
    state: "NV",
    controlNumber: "NV.0125.07.00",
    programTitle:
      "HCBS Waiver for Individuals with Intellectual and Developmental Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "lasNar",
    state: "NV",
    controlNumber: "NV.2426.00.00",
    programTitle: "Waiver for Structured Family Giving",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "17o46I",
    state: "NV",
    controlNumber: "NV.0152.07.05",
    programTitle: "Waiver for the Frail Elderly",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "uFG03S",
    state: "NV",
    controlNumber: "NV-20-0003",
    programTitle: "Specialized Foster Care",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "fJr0xB",
    state: "NV",
    controlNumber: "NV-24-0024",
    programTitle: "1915(i) HCBS State Plan Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "TpZSj0",
    state: "NY",
    controlNumber: "NY.4125.06.00",
    programTitle: "Childrenâ€™s Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "POI5j2",
    state: "NY",
    controlNumber: "NY.0269.05.00",
    programTitle: "TBI Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "oZJEyx",
    state: "NY",
    controlNumber: "NY.0444.02.11",
    programTitle: "Nursing Home Transition & Diversion Medicaid waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "DE7nQa",
    state: "NY",
    controlNumber: "NY.0238.06.06",
    programTitle: "NYS OPWDD Comprehensive Renewal Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "YULIG8",
    state: "NY",
    controlNumber: "11-W-00114/2",
    programTitle: "Medicaid Redesign Team",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "Wvb24S",
    state: "NY",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    id: "8ubeMV",
    state: "OH",
    controlNumber: "OH.0337.05.01",
    programTitle: "Ohio Home Care Waiver Amendment Jan. 1, 2022",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "7QFjRw",
    state: "OH",
    controlNumber: "OH.0380.04.03",
    programTitle: "Level One Waiver Amendment July 1, 2022",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "PrwvzZ",
    state: "OH",
    controlNumber: "OH.2226.00.00",
    programTitle: "OhioRISE Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Yjj96S",
    state: "OH",
    controlNumber: "OH.0198.06.07",
    programTitle: "PASSPORT Amendment Jan. 1 2022",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "QW6DaM",
    state: "OH",
    controlNumber: "OH.1035.01.05",
    programTitle:
      "Integrated Care Delivery System (ICDS) Waiver (MyCare Ohio) - 2021 Amendment",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "4rYaHm",
    state: "OH",
    controlNumber: "OH.0231.05.10",
    programTitle: "IO Waiver Amendment July 1, 2022",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Rf1DNX",
    state: "OH",
    controlNumber: "OH.0446.03.05",
    programTitle: "Assisted Living Amendment Jan. 1, 2022",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "vlydF2",
    state: "OH",
    controlNumber: "OH.0877.02.08",
    programTitle:
      "Self Empowered Life Funding (SELF) Waiver Amendment July 1, 2022",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "ID3vON",
    state: "OH",
    controlNumber: "OH-21-0006",
    programTitle: "HCBS Option-Specialist Recovery Services Program",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "2RmJAo",
    state: "OK",
    controlNumber: "OK.0179.07.05",
    programTitle: "Community Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "HUq36X",
    state: "OK",
    controlNumber: "OK.0256.06.04",
    programTitle: "ADvantage",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "a2lCFU",
    state: "OK",
    controlNumber: "OK.0399.04.05",
    programTitle: "Homeward Bound Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "5f5fdL",
    state: "OK",
    controlNumber: "OK.0343.05.01",
    programTitle: "In-Home Supports Waiver for Adults",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "kdUvUZ",
    state: "OK",
    controlNumber: "OK.0351.05.01",
    programTitle: "In-Home Supports Waiver for Children",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "ZHiGzt",
    state: "OK",
    controlNumber: "OK.0811.02.09",
    programTitle: "Medically Fragile",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "PIw2k9",
    state: "OR",
    controlNumber: "OR.0565.03.02",
    programTitle: "Medically Involved Children's Waiver (MICW)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "kURNdE",
    state: "OR",
    controlNumber: "OR.0185.07.00",
    programTitle: "Aged and Physically Disabled Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "x6v5V1",
    state: "OR",
    controlNumber: "OR.0117.06.12",
    programTitle: "Children's HCBS Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "If60ha",
    state: "OR",
    controlNumber: "OR.0375.04.08",
    programTitle: "Adults' HCBS Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "cX4e5i",
    state: "OR",
    controlNumber: "OR.2386.R00.00",
    programTitle: "Children's Extraordinary Needs Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "N799yK",
    state: "OR",
    controlNumber: "OR.40193.04.12",
    programTitle: "Medically Fragile (Hospital) Model",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "ct14bd",
    state: "OR",
    controlNumber: "OR.40194.04.08",
    programTitle: "Behavioral (ICF/IDD) Model Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "wQ673F",
    state: "OR",
    controlNumber: "OR-21-0013",
    programTitle: "1915(i) HCBS State Plan Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "gxXtCL",
    state: "OR",
    controlNumber: "11-W-00385/10",
    programTitle: "Oregon Project Independence Medicaid",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "Zaigog",
    state: "OR",
    controlNumber: "",
    programTitle: "1915(j) Self-directed 1915(c) waiver services",
    waiverType: WaiverType.SPA1915J,
  },
  {
    id: "XCl1m4",
    state: "OR",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    id: "jrOsC9",
    state: "PA",
    controlNumber: "PA.0386.04.12",
    programTitle: "Community HealthChoices",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "TAKRmj",
    state: "PA",
    controlNumber: "PA.0235.06.04",
    programTitle: "OBRA Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "CYArAj",
    state: "PA",
    controlNumber: "PA.0324.05.00",
    programTitle: "Medicaid Waiver for Infants, Toddlers and Families",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "tqh6it",
    state: "PA",
    controlNumber: "PA.0593.03.03",
    programTitle: "Pennsylvania Adult Autism Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "aopMHQ",
    state: "PA",
    controlNumber: "PA.0147.07.00",
    programTitle: "Consolidated Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "MNUTpK",
    state: "PA",
    controlNumber: "PA.0354.05.00",
    programTitle: "Person/Family Directed Support Waiver (P/FDS)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "tD4CMr",
    state: "PA",
    controlNumber: "PA.1486.01.00",
    programTitle: "Community Living Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Vcad1b",
    state: "RI",
    controlNumber: "11-W-00242/1",
    programTitle: "RI Global Consumer Choice Demonstration",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "bsiUJM",
    state: "SC",
    controlNumber: "SC.1686.00.02",
    programTitle:
      "Palmetto Coordinated System of Care for Children (PCSC) Home and Community Based Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "s3CgMc",
    state: "SC",
    controlNumber: "SC.0186.07.02",
    programTitle: "HIV/AIDS Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "6zMk23",
    state: "SC",
    controlNumber: "SC.0405.04.02",
    programTitle: "Community Choices",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "VKRf8o",
    state: "SC",
    controlNumber: "SC.0237.06.04",
    programTitle: "Intellectual Disability/Related Disabilities Waiver (ID/RD)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "LHaEiW",
    state: "SC",
    controlNumber: "SC.0675.03.02",
    programTitle: "Medically Complex Children",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "TDos92",
    state: "SC",
    controlNumber: "SC.0676.03.00",
    programTitle: "Community Supports (CS) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "9ML5Ie",
    state: "SC",
    controlNumber: "SC.40181.06.00",
    programTitle: "Mechanical Ventilator Dependent Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "Dfwvq2",
    state: "SC",
    controlNumber: "SC.0284.05.06",
    programTitle: "Head and Spinal Cord Injury (HASCI) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "sK0eTM",
    state: "SD",
    controlNumber: "SD.0189.07.00",
    programTitle:
      "Home and Community-Based Options and Person Centered Excellence (HOPE) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "AkALSb",
    state: "SD",
    controlNumber: "SD.0264.06.00",
    programTitle: "Assistive Daily Living Services Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "lgidiG",
    state: "SD",
    controlNumber: "SD.0338.05.00",
    programTitle: "South Dakota Family Support 360 Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "CStOcH",
    state: "SD",
    controlNumber: "SD.0044.08.09",
    programTitle: "CHOICES",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "psnQ9Q",
    state: "TN",
    controlNumber: "TN.0128.06.06",
    programTitle:
      "Statewide Home and Community Based Services (or â€œStatewideâ€) waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "4chSnE",
    state: "TN",
    controlNumber: "TN.0357.04.00",
    programTitle:
      'Comprehensive Aggregate Cap Home and Community Based Services (or CAC") Waiver"',
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "OPYSW1",
    state: "TN",
    controlNumber: "TN.0427.04.00",
    programTitle: "Tennessee Self-Determination Waiver Program",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "YGRq6o",
    state: "TN",
    controlNumber: "11-W-00369/4",
    programTitle: "TennCare III",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "Y6mWU8",
    state: "TX",
    controlNumber: "TX.0403.04.02",
    programTitle: "Texas Home Living Program",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "JiqJH3",
    state: "TX",
    controlNumber: "TX.0181.06.11",
    programTitle: "Medically Dependent Children Program (MDCP)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "C1oThW",
    state: "TX",
    controlNumber: "TX.0281.05.12",
    programTitle: "Deaf Blind with Multiple Disabilities",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "0mNDCv",
    state: "TX",
    controlNumber: "TX.0657.03.00",
    programTitle: "Youth Empowerment Services (YES)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "4nPdt3",
    state: "TX",
    controlNumber: "TX.0110.07.13",
    programTitle: "Home and Community-based Services (HCS) Program",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "urBnkc",
    state: "TX",
    controlNumber: "TX.0221.06.07",
    programTitle: "Community Living Assistance and Support Services (CLASS)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "9AIl5B",
    state: "TX",
    controlNumber: "TX-25-0008",
    programTitle: "Texas Adult Mental Health",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "vfLAEr",
    state: "TX",
    controlNumber: "11-W-00278/6",
    programTitle:
      "Texas Health Care Transformation and Quality Improvement Program",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "CMzbIc",
    state: "TX",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    id: "Gpayjh",
    state: "TX",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    id: "wxucOP",
    state: "UT",
    controlNumber: "UT.0331.05.04",
    programTitle: "Physical Disabilities Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "owKoNn",
    state: "UT",
    controlNumber: "UT.1886.00.03",
    programTitle: "Limited Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "KCgkck",
    state: "UT",
    controlNumber: "UT.1246.01.07",
    programTitle: "Medically Complex Children's Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "0PTVGr",
    state: "UT",
    controlNumber: "UT.40183.05.01",
    programTitle:
      "Waiver for Technology Dependent, Medically Fragile Individuals",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "lK0Yq7",
    state: "UT",
    controlNumber: "UT.0292.05.08",
    programTitle: "Acquired Brain Injury",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "4zsF9A",
    state: "UT",
    controlNumber: "UT.0158.07.07",
    programTitle:
      "Community Supports Waiver for Individuals with Intellectual Disabilities & Other Related Conditions",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "BK6HPA",
    state: "UT",
    controlNumber: "UT.0247.06.06",
    programTitle: "Waiver for Individuals Age 65 or Older",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "cyHWxY",
    state: "UT",
    controlNumber: "UT.0439.03.05",
    programTitle: "New Choices Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "a2Juhc",
    state: "UT",
    controlNumber: "UT.1666.00.06",
    programTitle: "Community Transitions Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "a26Tl9",
    state: "UT",
    controlNumber: "11-W-00145/8",
    programTitle: "Medicaid Refrom 1115 Demonstration",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "auJ6Kq",
    state: "VA",
    controlNumber: "VA.0358.04.12",
    programTitle: "Family and Individual Support Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "DYKPsO",
    state: "VA",
    controlNumber: "VA.0430.03.10",
    programTitle: "Building Independence Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "qqaC5f",
    state: "VA",
    controlNumber: "VA.0321.04.12",
    programTitle: "Commonwealth Coordinated Care Plus",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "fnqB8j",
    state: "VA",
    controlNumber: "VA.0372.04.11",
    programTitle: "Community Living Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "V88TZb",
    state: "VT",
    controlNumber: "11-W-00194/1",
    programTitle: "Vermont Global Commitment to Health",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "w9uTdA",
    state: "WA",
    controlNumber: "WA.0409.04.01",
    programTitle: "Basic Plus",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "4A7nZF",
    state: "WA",
    controlNumber: "WA.0410.04.01",
    programTitle: "Core Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "94V2Wi",
    state: "WA",
    controlNumber: "WA.0411.04.01",
    programTitle: "Community Protection Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "KuTdML",
    state: "WA",
    controlNumber: "WA.40669.03.01",
    programTitle: "Children's Intensive In-Home Behavioral Support",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "0MVSIa",
    state: "WA",
    controlNumber: "WA.0049.08.11",
    programTitle: "COPES",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "fvFIqj",
    state: "WA",
    controlNumber: "WA.1086.01.08",
    programTitle: "Residential Support Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "ggkdeB",
    state: "WA",
    controlNumber: "WA.1186.01.10",
    programTitle: "Individual and Family Services",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "LAdm7e",
    state: "WA",
    controlNumber: "WA.0443.04.00",
    programTitle: "New Freedom",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "MQdgs7",
    state: "WA",
    controlNumber: "WA-24-0001",
    programTitle: "Chronic Mental Illness State Plan Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "WWV19V",
    state: "WA",
    controlNumber: "11-W-00304/0",
    programTitle: "Medicaid Transformation Project (MTP)",
    waiverType: WaiverType.DEMO1115,
  },
  {
    id: "Ubtl5Q",
    state: "WA",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    id: "KTBHRl",
    state: "WI",
    controlNumber: "WI.0484.03.00",
    programTitle: "IRIS (Include, Respect, I Self-Direct) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "mr4bWX",
    state: "WI",
    controlNumber: "WI.0414.04.01",
    programTitle: "Children's Long-Term Support Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "CdR7yT",
    state: "WI",
    controlNumber: "WI.0367.04.00",
    programTitle: "Family Care Waiver Renewal 2020",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "S8yDI3",
    state: "WI",
    controlNumber: "WI-22-0019",
    programTitle: "Housing Assistance for Medicaid Eligible Individuals",
    waiverType: WaiverType.SPA1915I,
  },
  {
    id: "XexvbX",
    state: "WI",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    id: "7D4Kyg",
    state: "WV",
    controlNumber: "WV.1646.01.00",
    programTitle: "Children with Serious Emotional Disorder",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "L2T5Kd",
    state: "WV",
    controlNumber: "WV.0133.07.07",
    programTitle: "Intellectual/Developmental Disability Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "sXeU6h",
    state: "WV",
    controlNumber: "WV.0134.07.09",
    programTitle: "Aged and Disabled Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "zRlsl3",
    state: "WV",
    controlNumber: "WV.0876.02.07",
    programTitle: "Traumatic Brain Injury (TBI) Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "FHGPip",
    state: "WY",
    controlNumber: "WY.0236.06.06",
    programTitle: "Community Choices Waiver (CCW)",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "43xB30",
    state: "WY",
    controlNumber: "WY.1060.01.11",
    programTitle: "Supports Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "96PdpK",
    state: "WY",
    controlNumber: "WY.1061.01.10",
    programTitle: "Comprehensive Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
  {
    id: "TweCiw",
    state: "WY",
    controlNumber: "WY.0451.03.05",
    programTitle: "Children's Mental Health Waiver",
    waiverType: WaiverType.WAIVER1915C,
  },
];
