import { WAIVER, WaiverType } from "../../types/reports";

export const waivers: WAIVER[] = [
  {
    state: "AK",
    controlNumber: "AK.0260.06.02",
    programTitle: "People with Intellectual and Developmental Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AK",
    controlNumber: "AK.0261.06.00",
    programTitle: "Alaskans Living Independently",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AK",
    controlNumber: "AK.0262.06.02",
    programTitle: "Adults with Physical and Developmental Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AK",
    controlNumber: "AK.0262.06.02",
    programTitle: "Children with Complex Medical Conditions",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AK",
    controlNumber: "AK.1566.00.15",
    programTitle: "Individualized Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AK",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    state: "AL",
    controlNumber: "AL.0001.09.05",
    programTitle:
      "Alabama Home and Community-Based Waiver for Persons with Intellectual Disabilities (ID Waiver)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AL",
    controlNumber: "AL.0241.06.01",
    programTitle: "SAIL Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AL",
    controlNumber: "AL.0391.04.05",
    programTitle:
      "Alabama HCBS Living at Home Waiver for Persons with Intellectual Disabilities (LAH Waiver)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AL",
    controlNumber: "AL.0407.04.00",
    programTitle: "Technology Assisted Waiver-TA Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AL",
    controlNumber: "AL.0878.02.00",
    programTitle: "Alabama Community Transition Waiver (ACT Waiver)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AL",
    controlNumber: "AL.1746.00.01",
    programTitle: "Community Waiver Program",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AL",
    controlNumber: "AL.0068.08.00",
    programTitle:
      "Alabama Home and Community -Based Waiver for the Elderly and Disabled Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AL",
    controlNumber: "",
    programTitle: "1915(j) Self-directed 1915(c) waiver services",
    waiverType: WaiverType.SPA1915J,
  },
  {
    state: "AR",
    controlNumber: "AR.0195.06.02",
    programTitle: "ARChoices in Homecare",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AR",
    controlNumber: "AR.0400.04.00",
    programTitle: "Living Choices Assisted Living Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AR",
    controlNumber: "AR.0188.06.01",
    programTitle: "Community and Employment Support Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AR",
    controlNumber: "AR.0936.01.01",
    programTitle: "Autism Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "AR",
    controlNumber: "AR-23-0022",
    programTitle: "Adult Behavioral Health and Community Integration",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "AR",
    controlNumber: "AR-23-0021",
    programTitle: "PASSE",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "AR",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    state: "AR",
    controlNumber: "",
    programTitle: "1915(j) Self-directed 1915(c) waiver services",
    waiverType: WaiverType.SPA1915J,
  },
  {
    state: "AZ",
    controlNumber: "11-W-00275/9",
    programTitle: "Arizona Health Care Cost Containment System (AHCCCS)",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "CA",
    controlNumber: "CA.1166.01.00",
    programTitle:
      "California Self-Determination Program Waiver for Individuals with Developmental Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CA",
    controlNumber: "CA.0139.06.00",
    programTitle: "Home and Community Based Alternatives Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CA",
    controlNumber: "CA.0183.06.00",
    programTitle: "Medi-Cal Waiver Program (MCWP)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CA",
    controlNumber: "CA.0336.04.18",
    programTitle:
      "HCBS Waiver for Californians with Developmental Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CA",
    controlNumber: "CA.0431.03.09",
    programTitle: "California Assisted Living Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CA",
    controlNumber: "CA.0141.06.08",
    programTitle: "Multipurpose Senior Services Program",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CA",
    controlNumber: "CA-21-0002",
    programTitle: "Habilitation 1915(i) benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "CA",
    controlNumber: "11-W-00193/9",
    programTitle: "CalAIM",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "CA",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    state: "CA",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    state: "CO",
    controlNumber: "CO.0006.09.03",
    programTitle: "Elderly, Blind and Disabled (HCBS-EBD)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CO",
    controlNumber: "CO.0268.06.03",
    programTitle: "HCBS Waiver for Community Mental Health Supports (CMHS)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CO",
    controlNumber: "CO.0288.06.03",
    programTitle: "Persons with Brain Injury (HCBS-BI)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CO",
    controlNumber: "CO.4157.06.21",
    programTitle: "Children's Home and Community Based Services (CHCBS) waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CO",
    controlNumber: "CO.0007.08.21",
    programTitle: "Developmental Disabilities (HCBS-DD)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CO",
    controlNumber: "CO.0293.05.22",
    programTitle: "Supported Living Services (SLS)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CO",
    controlNumber: "CO.0305.05.21",
    programTitle: "HCBS - Children's Habilitation Residential Program",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CO",
    controlNumber: "CO.4180.05.21",
    programTitle: "Children's Extensive Support (CES) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CO",
    controlNumber: "CO.0450.03.14",
    programTitle:
      "Colorado's Home and Community Based Services Waiver for Children with Life-Limiting Illness",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CO",
    controlNumber: "CO.0961.02.16",
    programTitle: "Complementary and Integrative Health (HCBS-CIH)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CO",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    state: "CT",
    controlNumber: "CT.0140.07.00",
    programTitle: "Home and Community Based Services Waiver for Elders",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CT",
    controlNumber: "CT.0881.02.03",
    programTitle: "Employment and Day Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CT",
    controlNumber: "CT.0302.05.00",
    programTitle: "CT ABI Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CT",
    controlNumber: "CT.4110.08.00",
    programTitle: "Katie Beckett Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CT",
    controlNumber: "CT.0653.03.00",
    programTitle: "Mental Health Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CT",
    controlNumber: "CT.0993.02.00",
    programTitle: "Home and Community Supports Waiver for Persons with Autism",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CT",
    controlNumber: "CT.0426.04.00",
    programTitle: "Individual and Family Support Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CT",
    controlNumber: "CT.0437.03.10",
    programTitle: "Comprehensive Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CT",
    controlNumber: "CT.0301.06.00",
    programTitle: "Personal Care Assistance Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CT",
    controlNumber: "CT.1085.01.00",
    programTitle: "CT ABI Waiver II",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "CT",
    controlNumber: "CT-22-0001",
    programTitle: "Home Care Program for Elders (CHCPE)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "CT",
    controlNumber: "CT-21-0001",
    programTitle: "CT Housing Engagement & Support Services",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "CT",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    state: "DC",
    controlNumber: "DC.1766.00.05",
    programTitle: "Individual and Family Support (IFS) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "DC",
    controlNumber: "DC.0334.05.02",
    programTitle: "Elderly & Persons With Physical Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "DC",
    controlNumber: "DC.0307.05.01",
    programTitle:
      "People with Intellectual and Developmental Disabilities (IDD) Waiver - 2022 Renewal",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "DC",
    controlNumber: "DC-24-0019",
    programTitle: "Adult Day Health",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "DC",
    controlNumber: "DC-21-0015",
    programTitle: "Housing Support Services",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "DC",
    controlNumber: "DC-21-0011",
    programTitle: "Behavioral Health Supported Employment",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "DE",
    controlNumber: "DE.0009.08.06",
    programTitle: "DDDS Lifespan Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "DE",
    controlNumber: "DE-19-003",
    programTitle: "Pathways to Employment",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "DE",
    controlNumber: "11-W-00036/3",
    programTitle: "Diamond State Health Plan",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "FL",
    controlNumber: "FL.40205.03.00",
    programTitle: "Familial Dysautonomia Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "FL",
    controlNumber: "FL.0962.02.00",
    programTitle: "Florida Long-Term Care",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "FL",
    controlNumber: "FL.2346.00.00",
    programTitle:
      "Comprehensive Intellectual and Developmental Disabilities Managed Care Pilot Program",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "FL",
    controlNumber: "FL.0867.02.07",
    programTitle: "Developmental Disabilities Individual Budgeting Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "FL",
    controlNumber: "FL.40166.06.00",
    programTitle: "Model Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "FL",
    controlNumber: "11-W-00206/4",
    programTitle: "Managed Medical Assistance",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "FL",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    state: "FL",
    controlNumber: "",
    programTitle: "1915(j) Self-directed 1915(c) waiver services",
    waiverType: WaiverType.SPA1915J,
  },
  {
    state: "GA",
    controlNumber: "GA.0323.05.00",
    programTitle: "Comprehensive Supports Waiver Program",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "GA",
    controlNumber: "GA.4170.06.00",
    programTitle: "Independent Care Waiver Program (ICWP) renewal waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "GA",
    controlNumber: "GA.0112.08.00",
    programTitle: "Elderly and Disabled Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "GA",
    controlNumber: "GA.0175.06.01",
    programTitle: "New Options Waiver (NOW)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "HI",
    controlNumber: "HI.0013.08.03",
    programTitle:
      "HCB Services for People with Intellectual and Developmental Disabilities (I/DD Waiver)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "HI",
    controlNumber: "11-W-00001/9",
    programTitle: "Hawaii QUEST Integration",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "IA",
    controlNumber: "IA.0345.04.02",
    programTitle:
      "Home and Community Based Services - Physical Disability Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IA",
    controlNumber: "IA.4111.07.01",
    programTitle:
      "Home and Community Based Services - Health and Disability (HD) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IA",
    controlNumber: "IA.0819.02.07",
    programTitle: "The Children's Mental Health Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IA",
    controlNumber: "IA.4155.06.01",
    programTitle: "Home and Community Based Services - Elderly Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IA",
    controlNumber: "IA.0242.06.10",
    programTitle:
      "Home and Community Based Services - Intellectual Disabilities (ID) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IA",
    controlNumber: "IA.0299.05.06",
    programTitle: "Home and Community Based Services - Brain Injury (BI)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IA",
    controlNumber: "IA.0213.06.00",
    programTitle: "Home and Community Based Services - AIDS/HIV",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IA",
    controlNumber: "IA-16-0009",
    programTitle: "Habiliation",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "ID",
    controlNumber: "ID.0076.07.00",
    programTitle: "Adult Developmental Disabilities Waiver (renewal)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "ID",
    controlNumber: "ID.1076.07.00",
    programTitle: "Aged and Disabled Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "ID",
    controlNumber: "ID-20-0020",
    programTitle: "Children 1915(i)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "ID",
    controlNumber: "ID-22-0009",
    programTitle: "YES (children with SED)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "ID",
    controlNumber: "ID-22-0022",
    programTitle: "Adult DD",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "IL",
    controlNumber: "IL.0142.07.05",
    programTitle: "Persons with Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IL",
    controlNumber: "IL.0143.07.03",
    programTitle: "Persons who are Elderly",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IL",
    controlNumber: "IL.0329.05.02",
    programTitle: "Persons with Brain Injury",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IL",
    controlNumber: "IL.0350.05.01",
    programTitle: "Adults with Developmental Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IL",
    controlNumber: "IL.0464.03.01",
    programTitle:
      "Support Waiver for Children and Young Adults with Developmental Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IL",
    controlNumber: "IL.0473.03.01",
    programTitle:
      "Residential Waiver for Children and Young Adults with Developmental Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IL",
    controlNumber: "IL.0278.06.00",
    programTitle: "Medically Fragile, Technology Dependent",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IL",
    controlNumber: "IL.0326.05.00",
    programTitle: "Illinois Supportive Living Program",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IL",
    controlNumber: "IL.0202.06.14",
    programTitle: "Persons with HIV or AIDS",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IL",
    controlNumber: "IL-22-0021",
    programTitle: "1915(i) HCBS State Plan Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "IN",
    controlNumber: "IN.4197.05.00",
    programTitle: "Traumatic Brain Injury Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IN",
    controlNumber: "IN.0210.06.10",
    programTitle: "Aged & Disabled Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IN",
    controlNumber: "IN.2407.R00.00",
    programTitle: "Pathways Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IN",
    controlNumber: "IN.0378.04.06",
    programTitle: "Community Integration and Habilitation Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IN",
    controlNumber: "IN.0387.04.06",
    programTitle: "Family Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "IN",
    controlNumber: "IN-22-0016",
    programTitle: "Children's Mental Health Wraparound Benefit (CMHW)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "IN",
    controlNumber: "IN-23-0002",
    programTitle: "Adult mental Health Wraparound Benefit (AMHH)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "IN",
    controlNumber: "IN-23-0024",
    programTitle:
      "Behavioral and Primary Healthcare Coordination Benefit (BPHC)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "KS",
    controlNumber: "KS.0303.05.02",
    programTitle: "Home and Community Based Services for the Frail Elderly",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "KS",
    controlNumber: "KS.0304.05.02",
    programTitle: "Kansas Physical Disability Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "KS",
    controlNumber: "KS.0320.04.05",
    programTitle: "Serious Emotional Disturbance (SED) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "KS",
    controlNumber: "KS.0476.02.05",
    programTitle: "Autism Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "KS",
    controlNumber: "KS.4165.06.06",
    programTitle: "Technology Assisted Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "KS",
    controlNumber: "KS.0224.06.06",
    programTitle: "Kansas - HCBS-I/DD Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "KS",
    controlNumber: "KS.4164.06.07",
    programTitle: "Kansas HCBS Brain Injury Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "KY",
    controlNumber: "KY.0314.04.01",
    programTitle: "Supports for Community Living waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "KY",
    controlNumber: "KY.0333.04.00",
    programTitle: "Acquired Brain Injury Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "KY",
    controlNumber: "KY.0475.02.00",
    programTitle: "Michelle P. Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "KY",
    controlNumber: "KY.0477.02.00",
    programTitle: "Acquired Brain Injury, Long Term Care",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "KY",
    controlNumber: "KY.0144.07.00",
    programTitle: "Home and Community Based Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "KY",
    controlNumber: "KY.40146.07.00",
    programTitle: "Model Waiver II",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "KY",
    controlNumber: "KY-24-0010",
    programTitle: "SMI/SUD 1915i Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "LA",
    controlNumber: "LA.0401.04.01",
    programTitle: "New Opportunities Waiver (NOW)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "LA",
    controlNumber: "LA.0121.07.01",
    programTitle: "Adult Day Health Care (ADHC) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "LA",
    controlNumber: "LA.0889.02.00",
    programTitle:
      "Coordinated System of Care (CSoC) Severely Emotionally Disturbed (SED) Children's Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "LA",
    controlNumber: "LA.0472.03.00",
    programTitle: "Residential Options Waiver (ROW)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "LA",
    controlNumber: "LA.0361.04.12",
    programTitle: "Children's Choice (CC) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "LA",
    controlNumber: "LA.0453.03.14",
    programTitle: "Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "LA",
    controlNumber: "LA.0866.02.00",
    programTitle: "Community Choices (CC) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MA",
    controlNumber: "MA.1027.01.01",
    programTitle: "MFP Community Living (MFP-CL)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MA",
    controlNumber: "MA.1028.01.00",
    programTitle: "MFP Residential Supports (MFP-RS)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MA",
    controlNumber: "MA.40701.02.01",
    programTitle:
      "Acquired Brain Injury with Residential Habilitation (ABI-RH) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MA",
    controlNumber: "MA.40702.02.00",
    programTitle:
      "Acquired Brain Injury Non-Residential Habilitation (ABI-N) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MA",
    controlNumber: "MA.0826.02.08",
    programTitle: "Community Living Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MA",
    controlNumber: "MA.0827.02.08",
    programTitle: "Intensive Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MA",
    controlNumber: "MA.0828.02.08",
    programTitle: "Adult Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MA",
    controlNumber: "MA.0059.07.05",
    programTitle: "Frail Elder Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MA",
    controlNumber: "MA.0359.04.05",
    programTitle: "Traumatic Brain Injury Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MA",
    controlNumber: "MA.40207.04.00",
    programTitle: "Children's Autism Spectrum Disorder Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MD",
    controlNumber: "MD.40198.04.00",
    programTitle: "Brain Injury renewal waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MD",
    controlNumber: "MD.0265.06.00",
    programTitle: "Home and Community Based Options Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MD",
    controlNumber: "MD.0023.08.00",
    programTitle: "Community Pathways Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MD",
    controlNumber: "MD.0645.02.00",
    programTitle: "Medical Day Care Services Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MD",
    controlNumber: "MD.1466.02.01",
    programTitle: "Family Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MD",
    controlNumber: "MD.1506.02.00",
    programTitle: "Community Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MD",
    controlNumber: "MD.40118.07.00",
    programTitle: "Model Waiver for Fragile Children",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MD",
    controlNumber: "MD.0339.04.00",
    programTitle: "Waiver for Children with Autism Spectrum Disorder - Renewal",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MD",
    controlNumber: "MD-24-0008",
    programTitle: "Children & Youth W/SED",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "MD",
    controlNumber: "11-W-00099/3",
    programTitle: "HealthChoice",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "MD",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    state: "MD",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    state: "ME",
    controlNumber: "ME.0467.03.01",
    programTitle:
      "Support Services for Adults with Intellectual Disabilities or Autism Spectrum Disorder",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "ME",
    controlNumber: "ME.0276.05.06",
    programTitle: "Elderly and Adults with Disabilities Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "ME",
    controlNumber: "ME.0995.01.04",
    programTitle:
      "Home and Community Based Services for Adults with Other Related Conditions",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "ME",
    controlNumber: "ME.1082.01.03",
    programTitle:
      "Home and Community Based Services for Members with Brain Injury",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "ME",
    controlNumber: "ME.0159.07.06",
    programTitle:
      "Home and Community Services for Adults with Intellectual Disabilities or Autism Spectrum Disorder",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MI",
    controlNumber: "MI.1126.01.02",
    programTitle: "MI Health Link HCBS",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MI",
    controlNumber: "MI.0233.05.03",
    programTitle: "MI Choice Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MI",
    controlNumber: "MI.0167.06.00",
    programTitle: "Habilitation Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MI",
    controlNumber: "MI.0438.03.04",
    programTitle: "Waiver for Children with Serious Emotional Disturbances",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MI",
    controlNumber: "MI.4119.06.00",
    programTitle: "Children's Waiver Program",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MI",
    controlNumber: "MI-24-0008",
    programTitle: "Behavoiral Health",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "MI",
    controlNumber: "MI-23-0010",
    programTitle: "Nursing Facility Transition",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "MN",
    controlNumber: "MN.0166.07.14",
    programTitle: "Community Access for Disability Inclusion (CADI)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MN",
    controlNumber: "MN.4169.06.08",
    programTitle: "Brain Injury (BI) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MN",
    controlNumber: "MN.0061.08.01",
    programTitle: "Developmental Disabilities (DD) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MN",
    controlNumber: "MN.4128.07.21",
    programTitle: "Community Alternative Care (CAC) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MN",
    controlNumber: "MN.0025.08.22",
    programTitle: "Elderly Waiver (EW)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MN",
    controlNumber: "MN-24-0045",
    programTitle: "Housing Stabilization Services Benefit (HSS)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "MN",
    controlNumber: "MN-22-0006",
    programTitle: "Community First Services and Supports Benefit (CFSS)",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "MN",
    controlNumber: "11-W-00286/5",
    programTitle: "Minnesota Reform",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "MN",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    state: "MO",
    controlNumber: "MO.0178.07.05",
    programTitle: "DD Comprehensive Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MO",
    controlNumber: "MO.0404.04.05",
    programTitle: "Division of DD Community Support Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MO",
    controlNumber: "MO.1706.00.03",
    programTitle: "Structured Family Caregiving",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MO",
    controlNumber: "MO.40190.05.01",
    programTitle: "Medically Fragile Adult Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MO",
    controlNumber: "MO.0197.07.00",
    programTitle: "AIDS Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MO",
    controlNumber: "MO.0026.09.00",
    programTitle: "Aged & Disabled Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MO",
    controlNumber: "MO.0841.02.15",
    programTitle: "Partnership for Hope",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MO",
    controlNumber: "MO.4185.05.12",
    programTitle:
      "Missouri Children with Developmental Disabilities (MOCDD) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MO",
    controlNumber: "MO.0346.04.05",
    programTitle: "Independent Living Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MO",
    controlNumber: "MO.1021.03.00",
    programTitle: "Adult Day Care Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MO",
    controlNumber: "MO.1406.00.04",
    programTitle: "Brain Injury Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MS",
    controlNumber: "MS.0255.06.00",
    programTitle: "Independent Living Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MS",
    controlNumber: "MS.0272.06.00",
    programTitle: "Elderly and Disabled (E&D)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MS",
    controlNumber: "MS.0282.05.00",
    programTitle:
      "Intellectual Disabilities/Developmental Disabilities (ID/DD)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MS",
    controlNumber: "MS.0355.04.00",
    programTitle: "Assisted Living Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MS",
    controlNumber: "MS.0366.04.01",
    programTitle: "Traumatic Brain Injury/Spinal Cord Injury Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MS",
    controlNumber: "MS-23-0018",
    programTitle: "1915(i) HCBS State Plan Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "MT",
    controlNumber: "MT.0455.03.00",
    programTitle:
      "Severe and Disabling Mental Illness Home and Community Based Services",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MT",
    controlNumber: "MT.0208.06.09",
    programTitle:
      "Home and Community-Based Waiver for Individuals with Developmental Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MT",
    controlNumber: "MT.0148.06.08",
    programTitle: "Montana Big Sky",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "MT",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    state: "NC",
    controlNumber: "NC.1326.01.02",
    programTitle: "TBI Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NC",
    controlNumber: "NC.4141.07.00",
    programTitle: "Community Alternatives Program for Children",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NC",
    controlNumber: "NC.0423.03.10",
    programTitle: "North Carolina Innovations",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NC",
    controlNumber: "NC.0132.07.08",
    programTitle: "CAP/DA Renewal (3.5)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NC",
    controlNumber: "NC-22-0026",
    programTitle: "Mental Health/DD/SUD",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "ND",
    controlNumber: "ND.0568.03.00",
    programTitle: "North Dakota Medicaid Waiver for Medically Fragile Children",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "ND",
    controlNumber: "ND.0273.06.01",
    programTitle: "Medicaid Waiver for Home and Community Based Services",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "ND",
    controlNumber: "ND.0834.02.01",
    programTitle: "Children's Hospice",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "ND",
    controlNumber: "ND.0842.02.05",
    programTitle: "Autism Spectrum Disorder (ASD) Birth through Fifteen",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "ND",
    controlNumber: "ND.0037.08.04",
    programTitle: "Traditional IID/DD Home and Community Based Services Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "ND",
    controlNumber: "ND-20-0010",
    programTitle: "1915(i) HCBS State Plan Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "NE",
    controlNumber: "NE.0187.07.03",
    programTitle:
      "HCBS Waiver for Aged and Adults and Children with Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NE",
    controlNumber: "NE.0394.04.00",
    programTitle: "Developmental Disabilities Day Services Waiver for Adults",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NE",
    controlNumber: "NE.2366.R00.00",
    programTitle: "Family Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NE",
    controlNumber: "NE.4154.07.00",
    programTitle: "Comprehensive Developmental Disabilities Services waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NE",
    controlNumber: "NE.40199.04.10",
    programTitle: "Traumatic Brain Injury",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NE",
    controlNumber: "NE-24-0005",
    programTitle: "Therapeutic Family Care Crisis Support Services",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "NH",
    controlNumber: "NH.0397.04.00",
    programTitle:
      "NH In Home Supports Waiver for Children with Developmental Disabilities: 2021 - 2025",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NH",
    controlNumber: "NH.0053.07.05",
    programTitle: "New Hampshire Developmental Disabilities Waiver 2021-2026",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NH",
    controlNumber: "NH.4177.06.05",
    programTitle: "NH Acquired Brain Disorder Waiver 2021-2026",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NH",
    controlNumber: "NH.0060.08.01",
    programTitle: "Choices for Independence Waiver Renewal: 2022--->2027",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NH",
    controlNumber: "NH 21-0027",
    programTitle: "Supportive Housing",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "NH",
    controlNumber: "NH-22-0038",
    programTitle: "Home and Community-Based Care for High-Risk Children w/ SED",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "NH",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    state: "NJ",
    controlNumber: "11-W-00279/2",
    programTitle: "NJ Family Health Care Comphrensive",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "NJ",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    state: "NM",
    controlNumber: "NM.1726.00.04",
    programTitle: "Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NM",
    controlNumber: "NM.0448.03.02",
    programTitle: "Mi Via - ICF/IDD Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NM",
    controlNumber: "NM.0173.07.02",
    programTitle: "Developmental Disabilities Waiver Program",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NM",
    controlNumber: "NM.0223.06.02",
    programTitle: "Medically Fragile Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NM",
    controlNumber: "11-W-00285/6",
    programTitle: "Turquoise Care",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "NV",
    controlNumber: "NV.4150.07.00",
    programTitle:
      "Home and Community Based Services (HCBS) Waiver for Persons with Physical Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NV",
    controlNumber: "NV.0125.07.00",
    programTitle:
      "HCBS Waiver for Individuals with Intellectual and Developmental Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NV",
    controlNumber: "NV.2426.00.00",
    programTitle: "Waiver for Structured Family Giving",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NV",
    controlNumber: "NV.0152.07.05",
    programTitle: "Waiver for the Frail Elderly",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NV",
    controlNumber: "NV-20-0003",
    programTitle: "Specialized Foster Care",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "NV",
    controlNumber: "NV-24-0024",
    programTitle: "1915(i) HCBS State Plan Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "NY",
    controlNumber: "NY.4125.06.00",
    programTitle: "Childrenâ€™s Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NY",
    controlNumber: "NY.0269.05.00",
    programTitle: "TBI Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NY",
    controlNumber: "NY.0444.02.11",
    programTitle: "Nursing Home Transition & Diversion Medicaid waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NY",
    controlNumber: "NY.0238.06.06",
    programTitle: "NYS OPWDD Comprehensive Renewal Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "NY",
    controlNumber: "11-W-00114/2",
    programTitle: "Medicaid Redesign Team",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "NY",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    state: "OH",
    controlNumber: "OH.0337.05.01",
    programTitle: "Ohio Home Care Waiver Amendment Jan. 1, 2022",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OH",
    controlNumber: "OH.0380.04.03",
    programTitle: "Level One Waiver Amendment July 1, 2022",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OH",
    controlNumber: "OH.2226.00.00",
    programTitle: "OhioRISE Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OH",
    controlNumber: "OH.0198.06.07",
    programTitle: "PASSPORT Amendment Jan. 1 2022",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OH",
    controlNumber: "OH.1035.01.05",
    programTitle:
      "Integrated Care Delivery System (ICDS) Waiver (MyCare Ohio) - 2021 Amendment",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OH",
    controlNumber: "OH.0231.05.10",
    programTitle: "IO Waiver Amendment July 1, 2022",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OH",
    controlNumber: "OH.0446.03.05",
    programTitle: "Assisted Living Amendment Jan. 1, 2022",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OH",
    controlNumber: "OH.0877.02.08",
    programTitle:
      "Self Empowered Life Funding (SELF) Waiver Amendment July 1, 2022",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OH",
    controlNumber: "OH-21-0006",
    programTitle: "HCBS Option-Specialist Recovery Services Program",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "OK",
    controlNumber: "OK.0179.07.05",
    programTitle: "Community Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OK",
    controlNumber: "OK.0256.06.04",
    programTitle: "ADvantage",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OK",
    controlNumber: "OK.0399.04.05",
    programTitle: "Homeward Bound Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OK",
    controlNumber: "OK.0343.05.01",
    programTitle: "In-Home Supports Waiver for Adults",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OK",
    controlNumber: "OK.0351.05.01",
    programTitle: "In-Home Supports Waiver for Children",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OK",
    controlNumber: "OK.0811.02.09",
    programTitle: "Medically Fragile",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OR",
    controlNumber: "OR.0565.03.02",
    programTitle: "Medically Involved Children's Waiver (MICW)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OR",
    controlNumber: "OR.0185.07.00",
    programTitle: "Aged and Physically Disabled Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OR",
    controlNumber: "OR.0117.06.12",
    programTitle: "Children's HCBS Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OR",
    controlNumber: "OR.0375.04.08",
    programTitle: "Adults' HCBS Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OR",
    controlNumber: "OR.2386.R00.00",
    programTitle: "Children's Extraordinary Needs Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OR",
    controlNumber: "OR.40193.04.12",
    programTitle: "Medically Fragile (Hospital) Model",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OR",
    controlNumber: "OR.40194.04.08",
    programTitle: "Behavioral (ICF/IDD) Model Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "OR",
    controlNumber: "OR-21-0013",
    programTitle: "1915(i) HCBS State Plan Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "OR",
    controlNumber: "11-W-00385/10",
    programTitle: "Oregon Project Independence Medicaid",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "OR",
    controlNumber: "",
    programTitle: "1915(j) Self-directed 1915(c) waiver services",
    waiverType: WaiverType.SPA1915J,
  },
  {
    state: "OR",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    state: "PA",
    controlNumber: "PA.0386.04.12",
    programTitle: "Community HealthChoices",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "PA",
    controlNumber: "PA.0235.06.04",
    programTitle: "OBRA Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "PA",
    controlNumber: "PA.0324.05.00",
    programTitle: "Medicaid Waiver for Infants, Toddlers and Families",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "PA",
    controlNumber: "PA.0593.03.03",
    programTitle: "Pennsylvania Adult Autism Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "PA",
    controlNumber: "PA.0147.07.00",
    programTitle: "Consolidated Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "PA",
    controlNumber: "PA.0354.05.00",
    programTitle: "Person/Family Directed Support Waiver (P/FDS)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "PA",
    controlNumber: "PA.1486.01.00",
    programTitle: "Community Living Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "RI",
    controlNumber: "11-W-00242/1",
    programTitle: "RI Global Consumer Choice Demonstration",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "SC",
    controlNumber: "SC.1686.00.02",
    programTitle:
      "Palmetto Coordinated System of Care for Children (PCSC) Home and Community Based Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "SC",
    controlNumber: "SC.0186.07.02",
    programTitle: "HIV/AIDS Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "SC",
    controlNumber: "SC.0405.04.02",
    programTitle: "Community Choices",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "SC",
    controlNumber: "SC.0237.06.04",
    programTitle: "Intellectual Disability/Related Disabilities Waiver (ID/RD)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "SC",
    controlNumber: "SC.0675.03.02",
    programTitle: "Medically Complex Children",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "SC",
    controlNumber: "SC.0676.03.00",
    programTitle: "Community Supports (CS) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "SC",
    controlNumber: "SC.40181.06.00",
    programTitle: "Mechanical Ventilator Dependent Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "SC",
    controlNumber: "SC.0284.05.06",
    programTitle: "Head and Spinal Cord Injury (HASCI) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "SD",
    controlNumber: "SD.0189.07.00",
    programTitle:
      "Home and Community-Based Options and Person Centered Excellence (HOPE) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "SD",
    controlNumber: "SD.0264.06.00",
    programTitle: "Assistive Daily Living Services Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "SD",
    controlNumber: "SD.0338.05.00",
    programTitle: "South Dakota Family Support 360 Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "SD",
    controlNumber: "SD.0044.08.09",
    programTitle: "CHOICES",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "TN",
    controlNumber: "TN.0128.06.06",
    programTitle:
      "Statewide Home and Community Based Services (or â€œStatewideâ€) waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "TN",
    controlNumber: "TN.0357.04.00",
    programTitle:
      'Comprehensive Aggregate Cap Home and Community Based Services (or CAC") Waiver"',
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "TN",
    controlNumber: "TN.0427.04.00",
    programTitle: "Tennessee Self-Determination Waiver Program",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "TN",
    controlNumber: "11-W-00369/4",
    programTitle: "TennCare III",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "TX",
    controlNumber: "TX.0403.04.02",
    programTitle: "Texas Home Living Program",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "TX",
    controlNumber: "TX.0181.06.11",
    programTitle: "Medically Dependent Children Program (MDCP)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "TX",
    controlNumber: "TX.0281.05.12",
    programTitle: "Deaf Blind with Multiple Disabilities",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "TX",
    controlNumber: "TX.0657.03.00",
    programTitle: "Youth Empowerment Services (YES)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "TX",
    controlNumber: "TX.0110.07.13",
    programTitle: "Home and Community-based Services (HCS) Program",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "TX",
    controlNumber: "TX.0221.06.07",
    programTitle: "Community Living Assistance and Support Services (CLASS)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "TX",
    controlNumber: "TX-25-0008",
    programTitle: "Texas Adult Mental Health",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "TX",
    controlNumber: "11-W-00278/6",
    programTitle:
      "Texas Health Care Transformation and Quality Improvement Program",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "TX",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    state: "TX",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    state: "UT",
    controlNumber: "UT.0331.05.04",
    programTitle: "Physical Disabilities Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "UT",
    controlNumber: "UT.1886.00.03",
    programTitle: "Limited Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "UT",
    controlNumber: "UT.1246.01.07",
    programTitle: "Medically Complex Children's Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "UT",
    controlNumber: "UT.40183.05.01",
    programTitle:
      "Waiver for Technology Dependent, Medically Fragile Individuals",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "UT",
    controlNumber: "UT.0292.05.08",
    programTitle: "Acquired Brain Injury",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "UT",
    controlNumber: "UT.0158.07.07",
    programTitle:
      "Community Supports Waiver for Individuals with Intellectual Disabilities & Other Related Conditions",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "UT",
    controlNumber: "UT.0247.06.06",
    programTitle: "Waiver for Individuals Age 65 or Older",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "UT",
    controlNumber: "UT.0439.03.05",
    programTitle: "New Choices Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "UT",
    controlNumber: "UT.1666.00.06",
    programTitle: "Community Transitions Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "UT",
    controlNumber: "11-W-00145/8",
    programTitle: "Medicaid Refrom 1115 Demonstration",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "VA",
    controlNumber: "VA.0358.04.12",
    programTitle: "Family and Individual Support Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "VA",
    controlNumber: "VA.0430.03.10",
    programTitle: "Building Independence Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "VA",
    controlNumber: "VA.0321.04.12",
    programTitle: "Commonwealth Coordinated Care Plus",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "VA",
    controlNumber: "VA.0372.04.11",
    programTitle: "Community Living Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "VT",
    controlNumber: "11-W-00194/1",
    programTitle: "Vermont Global Commitment to Health",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "WA",
    controlNumber: "WA.0409.04.01",
    programTitle: "Basic Plus",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WA",
    controlNumber: "WA.0410.04.01",
    programTitle: "Core Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WA",
    controlNumber: "WA.0411.04.01",
    programTitle: "Community Protection Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WA",
    controlNumber: "WA.40669.03.01",
    programTitle: "Children's Intensive In-Home Behavioral Support",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WA",
    controlNumber: "WA.0049.08.11",
    programTitle: "COPES",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WA",
    controlNumber: "WA.1086.01.08",
    programTitle: "Residential Support Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WA",
    controlNumber: "WA.1186.01.10",
    programTitle: "Individual and Family Services",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WA",
    controlNumber: "WA.0443.04.00",
    programTitle: "New Freedom",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WA",
    controlNumber: "WA-24-0001",
    programTitle: "Chronic Mental Illness State Plan Benefit",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "WA",
    controlNumber: "11-W-00304/0",
    programTitle: "Medicaid Transformation Project (MTP)",
    waiverType: WaiverType.DEMO1115,
  },
  {
    state: "WA",
    controlNumber: "",
    programTitle: "1915(k) Community First Choice",
    waiverType: WaiverType.SPA1015K,
  },
  {
    state: "WI",
    controlNumber: "WI.0484.03.00",
    programTitle: "IRIS (Include, Respect, I Self-Direct) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WI",
    controlNumber: "WI.0414.04.01",
    programTitle: "Children's Long-Term Support Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WI",
    controlNumber: "WI.0367.04.00",
    programTitle: "Family Care Waiver Renewal 2020",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WI",
    controlNumber: "WI-22-0019",
    programTitle: "Housing Assistance for Medicaid Eligible Individuals",
    waiverType: WaiverType.SPA1915I,
  },
  {
    state: "WI",
    controlNumber: "",
    programTitle: "1915(j) Self-directed state plan PCS",
    waiverType: WaiverType.SPA1915J,
  },
  {
    state: "WV",
    controlNumber: "WV.1646.01.00",
    programTitle: "Children with Serious Emotional Disorder",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WV",
    controlNumber: "WV.0133.07.07",
    programTitle: "Intellectual/Developmental Disability Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WV",
    controlNumber: "WV.0134.07.09",
    programTitle: "Aged and Disabled Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WV",
    controlNumber: "WV.0876.02.07",
    programTitle: "Traumatic Brain Injury (TBI) Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WY",
    controlNumber: "WY.0236.06.06",
    programTitle: "Community Choices Waiver (CCW)",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WY",
    controlNumber: "WY.1060.01.11",
    programTitle: "Supports Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WY",
    controlNumber: "WY.1061.01.10",
    programTitle: "Comprehensive Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
  {
    state: "WY",
    controlNumber: "WY.0451.03.05",
    programTitle: "Children's Mental Health Waiver",
    waiverType: WaiverType.WAVIER1915C,
  },
];
