services:
  # wave 1: no dependencies
  # database: # IMPORT DONE
  # path: services/database
  # topics:
  #   path: services/topics
  ui: # IMPORT DONE
    path: services/ui
  # uploads:
  #   path: services/uploads

  # wave 2: depends on database
  app-api:
    path: services/app-api
    params:
      BannerTableName: ${database.BannerTableName}
      QmsReportTableName: ${database.QmsReportTableName}

  # wave 3: depends on many
  ui-auth: # IMPORT DONE
    path: services/ui-auth
    params:
      ApiGatewayRestApiName: ${app-api.ApiGatewayRestApiName}
      ApplicationEndpointUrl: ${ui.ApplicationEndpointUrl}

  # wave 4: depends on most
  ui-src:
    path: services/ui-src
    params:
      ApiRegion: ${app-api.Region}
      ApiGatewayRestApiUrl: ${app-api.ApiGatewayRestApiUrl}
      CognitoRegion: ${ui-auth.Region}
      IdentityPoolId: ${ui-auth.IdentityPoolId}
      UserPoolId: ${ui-auth.UserPoolId}
      UserPoolClientId: ${ui-auth.UserPoolClientId}
      UserPoolClientDomain: ${ui-auth.UserPoolClientDomain}
      IdentityProvider: ${ui-auth.IdentityProvider}
      S3BucketName: ${ui.S3BucketName}
      CloudFrontDistributionId: ${ui.CloudFrontDistributionId}
      ApplicationEndpointUrl: ${ui.ApplicationEndpointUrl}
