import {
  PageType,
  ElementType,
  MeasureTemplateName,
  MeasurePageTemplate,
} from "../../../types/reports";
import {
  additionalNotesField,
  didYouFollowSpecifications,
  isTheStateReportingThisMeasure,
  measureDetailsSection,
  measureFooter,
  measureHeader,
  measureInformationSubheader,
  measureInstructions,
  deliveryMethodMeasureInstructions,
  enterMeasureResultsSubheader,
  measureResultsNavigationTable,
  returnToOptionalDashboard,
  returnToRequiredDashboard,
  wereTheResultsAudited,
  whatSpecificationsAreYouUsing,
  measureDeliveryMethodsSubheader,
  whichVersionQualityMeasureReported,
  whichProgramsWaivers,
  feeForServiceMeasureResultsSubheader,
  managedCareMeasureResultsSubheader,
  exclusionRatesAssessmentElements,
  performanceRatesAssessmentElements,
  performanceRatesPersonPlanElements,
  exclusionRatesPersonPlanElements,
  performanceRateTermStay,
  performanceRateFacilityDischarges,
  performanceRateFacilityTransitions,
  performanceRateSelfDirection,
  returnToDashboard,
  divider,
  measureCompleteBanner,
  sectionCompleteBanner,
  performanceRatePOM,
  measureType,
  statePerformanceTargetLabel,
  stateExclusionTargetLabel,
} from "../elements";

export const measureTemplates: Record<
  MeasureTemplateName,
  Omit<MeasurePageTemplate, "cmitId" | "status">
> = {
  [MeasureTemplateName["LTSS-1"]]: {
    id: "LTSS-1",
    title: "LTSS-1: Comprehensive Assessment and Update",
    type: PageType.Measure,
    substitutable: MeasureTemplateName["FASI-1"],
    sidebar: false,
    elements: [
      returnToDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      whatSpecificationsAreYouUsing,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-1"]]: {
    id: "FFS-1",
    title: "LTSS-1: Fee-For-Service (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-1",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-1: Fee-For-Service (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatesAssessmentElements,
      exclusionRatesAssessmentElements,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-1",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-1"]]: {
    id: "MLTSS-1",
    title: "LTSS-1: Managed Care (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-1",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-1: Managed Care (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatesAssessmentElements,
      exclusionRatesAssessmentElements,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-1",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["LTSS-2"]]: {
    id: "LTSS-2",
    title: "LTSS-2: Comprehensive Person-Centered Plan and Update",
    type: PageType.Measure,
    sidebar: false,
    substitutable: MeasureTemplateName["FASI-2"],
    elements: [
      returnToDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      whatSpecificationsAreYouUsing,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-2"]]: {
    id: "FFS-2",
    title: "LTSS-2: Fee-For-Service (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-2",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-2: Fee-For-Service (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatesPersonPlanElements,
      exclusionRatesPersonPlanElements,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-2",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-2"]]: {
    id: "MLTSS-2",
    title: "LTSS-2: Managed Care (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-2",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-2: Managed Care (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatesPersonPlanElements,
      exclusionRatesPersonPlanElements,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-2",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["LTSS-6"]]: {
    id: "LTSS-6",
    title: "LTSS-6: Admission to a Facility from the Community",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToRequiredDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      isTheStateReportingThisMeasure,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-6"]]: {
    id: "FFS-6",
    title: "LTSS-6: Fee-For-Service (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-6",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-6: Fee-For-Service (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRateTermStay,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-6",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-6"]]: {
    id: "MLTSS-6",
    title: "LTSS-6: Managed Care (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-6",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-6: Managed Care (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRateTermStay,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-6",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["LTSS-7"]]: {
    id: "LTSS-7",
    title: "LTSS-7: Minimizing Facility Length of Stay",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToRequiredDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      isTheStateReportingThisMeasure,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-7"]]: {
    id: "FFS-7",
    title: "LTSS-7: Fee-For-Service (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-7",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-7: Fee-For-Service (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRateFacilityDischarges,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-7",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-7"]]: {
    id: "MLTSS-7",
    title: "LTSS-7: Managed Care (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-7",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-7: Managed Care (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRateFacilityDischarges,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-7",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["LTSS-8"]]: {
    id: "LTSS-8",
    title: "LTSS-8: Successful Transition after Long-Term Facility Stay",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToRequiredDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      isTheStateReportingThisMeasure,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-8"]]: {
    id: "FFS-8",
    title: "LTSS-8: Fee-For-Service (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-8",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-8: Fee-For-Service (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRateFacilityTransitions,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-8",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-8"]]: {
    id: "MLTSS-8",
    title: "LTSS-8: Managed Care (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-8",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-8: Managed Care (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRateFacilityTransitions,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-8",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["FASI-1"]]: {
    id: "FASI-1",
    title: "FASI-1: Identification of Person-Centered Priorities",
    substitutable: MeasureTemplateName["LTSS-1"],
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-FASI-1"]]: {
    id: "FFS-FASI-1",
    title: "FASI-1: Fee-For-Service (FFS FASI-1)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "FASI-1",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "FASI-1: Fee-For-Service (FFS FASI-1)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      {
        type: ElementType.Ndr,
        id: "measure-rates",
        required: true,
        label:
          "Participant who has Identified at Least as Many Total Personal Priorities as Functional Needs in the Areas of Self-Care, Mobility, or IADL",
        ...statePerformanceTargetLabel,
      },
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "FASI-1",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-FASI-1"]]: {
    id: "MLTSS-FASI-1",
    title: "FASI-1: Managed Care (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "FASI-1",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "FASI-1: Managed Care (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      {
        type: ElementType.Ndr,
        id: "measure-rates",
        required: true,
        label:
          "Participant who has Identified at Least as Many Total Personal Priorities as Functional Needs in the Areas of Self-Care, Mobility, or IADL",
        ...statePerformanceTargetLabel,
      },
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "FASI-1",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["FASI-2"]]: {
    id: "FASI-2",
    title: "FASI-2: Documentation of a Person-Centered Service Plan",
    type: PageType.Measure,
    substitutable: MeasureTemplateName["LTSS-2"],
    sidebar: false,
    elements: [
      returnToDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-FASI-2"]]: {
    id: "FFS-FASI-2",
    title: "FASI-2: Fee-For-Service (FFS FASI-2)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "FASI-2",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "FASI-2: Fee-For-Service (FFS FASI-2)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      {
        type: ElementType.Ndr,
        id: "measure-rates",
        required: true,
        label:
          "Participant whose Person-Centered Service Plan Documentation Addresses Needs in the Areas of Self-Care, Mobility, and IADL",
        ...statePerformanceTargetLabel,
      },
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "FASI-2",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-FASI-2"]]: {
    id: "MLTSS-FASI-2",
    title: "FASI-2: Managed Care (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "FASI-2",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "FASI-2: Managed Care (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      {
        type: ElementType.Ndr,
        id: "measure-rates",
        label:
          "Participant whose Person-Centered Service Plan Documentation Addresses Needs in the Areas of Self-Care, Mobility, and IADL",
        ...statePerformanceTargetLabel,
        required: true,
      },
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "FASI-2",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["HCBS-10"]]: {
    id: "HCBS-10",
    title:
      "HCBS-10: Self-direction of Services and Supports Among Medicaid Beneficiaries Receiving LTSS through Managed Care Organizations",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToOptionalDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["MLTSS-HCBS-10"]]: {
    id: "MLTSS-HCBS-10",
    title: "HCBS-10: Managed Care (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "HCBS-10",
      },
      {
        ...measureHeader,
        text: "HCBS-10: Managed Care (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRateSelfDirection,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "HCBS-10",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["LTSS-3"]]: {
    id: "LTSS-3",
    title: "LTSS-3: Shared Person-Centered Plan with Primary Care Provider",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToOptionalDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      whatSpecificationsAreYouUsing,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-3"]]: {
    id: "FFS-3",
    title: "LTSS-3: Fee-For-Service (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-3",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-3: Fee-For-Service (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      divider,
      {
        type: ElementType.NdrEnhanced,
        id: "measure-rates",
        ...statePerformanceTargetLabel,
        required: true,
        assessments: [
          {
            id: "pc-plan",
            label: "Participant with Person-Centered Plan Transmitted to PCP",
          },
        ],
      },
      {
        type: ElementType.NdrEnhanced,
        id: "measure-rates",
        label: "Exclusion Rate",
        required: true,
        ...stateExclusionTargetLabel,
        assessments: [
          {
            id: "refused-pc-plan",
            label: "Participant Refused to Share Person-Centered Plan",
          },
        ],
      },
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-3",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-3"]]: {
    id: "MLTSS-3",
    title: "LTSS-3: Managed Care (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-3",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-3: Managed Care (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      divider,
      {
        type: ElementType.NdrEnhanced,
        id: "measure-rates",
        ...statePerformanceTargetLabel,
        required: true,
        assessments: [
          {
            id: "pc-plan",
            label: "Participant with Person-Centered Plan Transmitted to PCP",
          },
        ],
      },
      {
        type: ElementType.NdrEnhanced,
        id: "measure-rates",
        label: "Exclusion Rate",
        required: true,
        ...stateExclusionTargetLabel,
        assessments: [
          {
            id: "refused-pc-plan",
            label: "Participant Refused to Share Person-Centered Plan",
          },
        ],
      },
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-3",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["LTSS-4"]]: {
    id: "LTSS-4",
    title:
      "LTSS-4: Reassessment and Person-Centered Plan Update after Inpatient Discharge",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToOptionalDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      whatSpecificationsAreYouUsing,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-4"]]: {
    id: "FFS-4",
    title: "LTSS-4: Fee-For-Service (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-4",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-4: Fee-For-Service (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatesAssessmentElements,
      exclusionRatesAssessmentElements,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-4",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-4"]]: {
    id: "MLTSS-4",
    title: "LTSS-4: Managed Care (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "LTSS-4",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "LTSS-4: Managed Care (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatesAssessmentElements,
      exclusionRatesAssessmentElements,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "LTSS-4",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-5"]]: {
    id: "MLTSS-5",
    title:
      "MLTSS-5: Screening, Risk Assessment, and Plan of Care to Prevent Future Falls",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToOptionalDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["MLTSS-5-PT1"]]: {
    id: "MLTSS-5-PT1",
    title: "MLTSS-5 Part 1: Screening (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "MLTSS-5",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "MLTSS-5 Part 1: Screening (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      {
        type: ElementType.NdrEnhanced,
        id: "measure-rates",
        ...statePerformanceTargetLabel,
        required: true,
        assessments: [
          {
            id: "gait-evaulation",
            label: "Fall or Problems with Balance or Gait Evaluation",
          },
        ],
      },
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "MLTSS-5",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-5-PT2"]]: {
    id: "MLTSS-5-PT2",
    title: "MLTSS-5 Part 2: Risk Assessment and Plan of Care (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "MLTSS-5",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "MLTSS-5 Part 2: Risk Assessment and Plan of Care (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      {
        type: ElementType.NdrEnhanced,
        id: "measure-rates",
        ...statePerformanceTargetLabel,
        required: true,
        assessments: [
          {
            id: "fall-risk-assess",
            label: "Falls Risk Assessment",
          },
          {
            id: "plan-care-falls",
            label: "Plan of Care for Falls",
          },
        ],
      },
      {
        type: ElementType.NdrEnhanced,
        id: "measure-rates",
        required: true,
        label: "Exclusion Rate",
        ...stateExclusionTargetLabel,
        assessments: [
          {
            id: "refused-risk-assess",
            label: "Participant Refused Risk Assessment",
          },
        ],
      },
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "MLTSS-5",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS"]]: {
    id: "MLTSS",
    title: "MLTSS: Plan All-Cause Readmission",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToOptionalDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["MLTSS-DM"]]: {
    id: "MLTSS-DM",
    title: "MLTSS: Managed Care (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "MLTSS",
      },
      sectionCompleteBanner,
      measureType,
      deliveryMethodMeasureInstructions,
      {
        ...measureHeader,
        text: "MLTSS: Managed Care (MLTSS)",
      },
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      {
        type: ElementType.NdrEnhanced,
        id: "measure-rates",
        ...statePerformanceTargetLabel,
        required: true,
        assessments: [
          {
            id: "acute-readmission-plan",
            label:
              "Acute inpatient and observation stays during the measurement year that were followed by an unplanned acute readmission for any diagnosis within 30 days, for participants 65 years of age",
          },
        ],
      },
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "MLTSS",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["POM-1"]]: {
    id: "POM-1",
    title: "POM: People Live in Integrated Environments",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToRequiredDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-POM-1"]]: {
    id: "FFS-POM-1",
    title: "POM: People Live in Integrated Environments (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-1",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "POM: People Live in Integrated Environments (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-1",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-POM-1"]]: {
    id: "MLTSS-POM-1",
    title: "POM: People Live in Integrated Environments (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-1",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "POM: People Live in Integrated Environments (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-1",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["POM-2"]]: {
    id: "POM-2",
    title: "POM: People Participate in the Life of the Community",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToRequiredDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-POM-2"]]: {
    id: "FFS-POM-2",
    title: "POM: People Participate in the Life of the Community (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-2",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "POM: People Participate in the Life of the Community (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-2",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-POM-2"]]: {
    id: "MLTSS-POM-2",
    title: "POM: People Participate in the Life of the Community (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-2",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "POM: People Participate in the Life of the Community (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-2",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["POM-3"]]: {
    id: "POM-3",
    title: "POM: People Choose Services",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToRequiredDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-POM-3"]]: {
    id: "FFS-POM-3",
    title: "POM: People Choose Services (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-3",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "POM: People Choose Services (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-3",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-POM-3"]]: {
    id: "MLTSS-POM-3",
    title: "POM: People Choose Services (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-3",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "POM: People Choose Services (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-3",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["POM-4"]]: {
    id: "POM-4",
    title: "POM: People Realize Personal Goals",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToRequiredDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-POM-4"]]: {
    id: "FFS-POM-4",
    title: "POM: People Realize Personal Goals (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-4",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "POM: People Realize Personal Goals (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-4",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-POM-4"]]: {
    id: "MLTSS-POM-4",
    title: "POM: People Realize Personal Goals (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-4",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "POM: People Realize Personal Goals (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-4",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["POM-5"]]: {
    id: "POM-5",
    title: "POM: People are Free from Abuse and Neglect",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToRequiredDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-POM-5"]]: {
    id: "FFS-POM-5",
    title: "POM: People are Free from Abuse and Neglect (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-5",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "POM: People are Free from Abuse and Neglect (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-5",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-POM-5"]]: {
    id: "MLTSS-POM-5",
    title: "POM: People are Free from Abuse and Neglect (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-5",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "POM: People are Free from Abuse and Neglect (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-5",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["POM-6"]]: {
    id: "POM-6",
    title: "POM: People Have the Best Possible Health",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToOptionalDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-POM-6"]]: {
    id: "FFS-POM-6",
    title: "POM: People Have the Best Possible Health (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-6",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "POM: People Have the Best Possible Health (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-6",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-POM-6"]]: {
    id: "MLTSS-POM-6",
    title: "POM: People Have the Best Possible Health (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-6",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "POM: People Have the Best Possible Health (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-6",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["POM-7"]]: {
    id: "POM-7",
    title: "POM: People Interact with Other Members of the Community",
    type: PageType.Measure,
    sidebar: false,
    elements: [
      returnToOptionalDashboard,
      measureCompleteBanner,
      measureType,
      measureHeader,
      measureInstructions,
      measureDetailsSection,
      measureInformationSubheader,
      didYouFollowSpecifications,
      wereTheResultsAudited,
      additionalNotesField,
      ...measureDeliveryMethodsSubheader,
      whichVersionQualityMeasureReported,
      enterMeasureResultsSubheader,
      measureResultsNavigationTable,
      measureFooter,
    ],
  },
  [MeasureTemplateName["FFS-POM-7"]]: {
    id: "FFS-POM-7",
    title: "People Interact with Other Members of the Community (FFS LTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-7",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "People Interact with Other Members of the Community (FFS LTSS)",
      },
      deliveryMethodMeasureInstructions,
      feeForServiceMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-7",
        completeSection: true,
      },
    ],
  },
  [MeasureTemplateName["MLTSS-POM-7"]]: {
    id: "MLTSS-POM-7",
    title: "People Interact with Other Members of the Community (MLTSS)",
    type: PageType.MeasureResults,
    sidebar: false,
    elements: [
      {
        type: ElementType.ButtonLink,
        id: "return-button",
        label: "Return to Measure Information",
        to: "POM-7",
      },
      sectionCompleteBanner,
      measureType,
      {
        ...measureHeader,
        text: "People Interact with Other Members of the Community (MLTSS)",
      },
      deliveryMethodMeasureInstructions,
      managedCareMeasureResultsSubheader,
      ...whichProgramsWaivers,
      performanceRatePOM,
      {
        type: ElementType.MeasureFooter,
        id: "measure-footer",
        prevTo: "POM-7",
        completeSection: true,
      },
    ],
  },
};
