name: Deploy

on:
  push:
    branches:
      - "*"
      - "dependabot/**"
      - "!skipci*"
      - "!code-json-*"

concurrency:
  group: ${{ github.ref_name }}

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'production' && 'production' ||
      github.ref_name == 'val' && 'val' || 'dev' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock', 'plugins/**') }}
      - name: path + branch settings + install packages
        run: |
          echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
          BRANCH_NAME=$(./.github/setBranchName.sh ${{ github.ref_name }})
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV
          ./.github/branchNameValidation.sh $branch_name
          ./run install
      - name: Configure AWS credentials for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - name: deploy
        run: |
          ./run deploy --stage $branch_name
      - id: endpoint
        run: |
          APPLICATION_ENDPOINT=$(./scripts/output.sh hcbs-$branch_name CloudFrontUrl)
          echo "application_endpoint=$APPLICATION_ENDPOINT" >> $GITHUB_OUTPUT
          echo "## Application Endpoint" >> $GITHUB_STEP_SUMMARY
          echo "<$APPLICATION_ENDPOINT>" >> $GITHUB_STEP_SUMMARY
      - name: Run Playwright tests
        if: ${{ github.ref_name != 'production' }}
        run: |
          yarn playwright install
          yarn playwright test --reporter=github
        working-directory: tests
        env:
          BASE_URL: ${{ steps.endpoint.outputs.application_endpoint}}
          TEST_STATE_USER_EMAIL: ${{ secrets.TEST_STATE_USER_EMAIL }}
          TEST_STATE_USER_PASSWORD: ${{ secrets.TEST_STATE_USER_PASSWORD }}
          TEST_ADMIN_USER_EMAIL: ${{ secrets.TEST_ADMIN_USER_EMAIL }}
          TEST_ADMIN_USER_PASSWORD: ${{ secrets.TEST_ADMIN_USER_PASSWORD }}
